# Dot product

### 1. np.array.squeeze( )

- 필요없는 차원을 줄여줌
    - axis=0 : 0차원이 '1'일 경우, 제거
    - axis 지정 X : 차원이 '1'인 것 모두 제거

In [3]:
a = np.random.randint(low=10,high=20,size=(1,2,3))
print(a,a.shape)

[[[16 11 16]
  [10 19 17]]] (1, 2, 3)


In [5]:
a.squeeze().shape

(2, 3)

In [6]:
a.squeeze(axis=0).shape

(2, 3)

In [9]:
a.squeeze(axis=0)

array([[16, 11, 16],
       [10, 19, 17]])

In [19]:
b = np.random.randint(low=10,high=20,size=(1,3,1,1))
print(b,b.shape)

[[[[14]]

  [[19]]

  [[15]]]] (1, 3, 1, 1)


In [20]:
print(b.squeeze(axis=0),b.squeeze(axis=0).shape)

[[[14]]

 [[19]]

 [[15]]] (3, 1, 1)


In [21]:
print(b.squeeze(axis=2),b.squeeze(axis=2).shape)

[[[14]
  [19]
  [15]]] (1, 3, 1)


In [22]:
print(b.squeeze(axis=2),b.squeeze(axis=3).shape)

[[[14]
  [19]
  [15]]] (1, 3, 1)


In [23]:
print(b.squeeze(),b.squeeze().shape)

[14 19 15] (3,)


### 2. Dot product

- v1.dot(v2)
- v1 @ v2
- scalar value가 되도록 squeeze( ) 활용

In [33]:
v1 = np.array([1,2,3]).reshape(-1,1)
v2 = np.array([10,20,30]).reshape(-1,1)
print(f"v1 : \n{v1}, \nv2 : \n{v2}",sep='\n')

v1 : 
[[1]
 [2]
 [3]], 
v2 : 
[[10]
 [20]
 [30]]


$Dot product : v1^{T} v2$ = scalar value

In [31]:
v1.T.dot(v2).squeeze()

array(140)

In [30]:
v1.T.dot(v2).squeeze().shape

()

In [37]:
(v1.T@v2).squeeze()

array(140)

In [36]:
(v1.T@v2).squeeze().shape

()