### 1. vector operation(+, -)

**python list + : concatenation (근본적으로 벡터 / 행렬 연산과 거리가 먼 자료구조)**

**ndarray + : entry addition**

In [3]:
a = [1,2,3,4]
b = [10,20,30,40]

a+b

[1, 2, 3, 4, 10, 20, 30, 40]

In [2]:
c = np.array(a)
d = np.array(b)

c+d

array([11, 22, 33, 44])

In [4]:
c-d

array([ -9, -18, -27, -36])

### 2. Broadcasting ( vector + scalar ) 

```
vector의 모든 element에 scalar를 복제해 operation!
```

In [5]:
a = np.array([1,2,3,4])
b = 10

a+b

array([11, 12, 13, 14])

In [6]:
a-b

array([-9, -8, -7, -6])

### 3. Broadcasting ( matrix + vector )
```
matrix에 vector의 행 또는 열을 그대로 복제해 operation!

ex) 3,2 mat / 3,1 vec
==> 3,1 vec의 1열을 2열로 복제해 3,2mat + 3,2vec* 를 연산함
```

In [12]:
a = np.random.randint(low=0,high=10,size=(3,2))
b = np.array([[100],[200],[300]])

print(f"a : \n{a}, \nb: \n{b}, \na+b : \n{a+b}")

a : 
[[0 3]
 [3 6]
 [9 7]], 
b: 
[[100]
 [200]
 [300]], 
a+b : 
[[100 103]
 [203 206]
 [309 307]]
