# Day 5 진도

- quiz
- 100에서 100까지 랜덤한 숫자를 갖는 8 8 행렬을 만들고
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환

[작업단위 처리순서]
- 1. 랜덤 행열 생성
- 2. 3배수 / 5배수 / 15배수의 True,False 행렬 저장
- 3. arr2의 형변환( .astype(str) )
- 4. arr2[True인 idx set] = 'fiz' 등으로 각각 문자열 넣기 <---- **브로드캐스팅** ! 

In [1]:
import numpy as np

In [2]:
# 1.
arr = np.random.randint(100,130,size=(8,8))
arr2 = arr.copy()
arr2

np.random.randint

<module 'numpy.random' from '/Users/kimjeongseob/opt/anaconda3/lib/python3.7/site-packages/numpy/random/__init__.py'>

In [26]:
# 2.
idx_3 = arr2%3==0
idx_5 = arr2%5==0
idx_15 = arr2%15==0

In [28]:
# 3. 형변환
arr3 = arr2.astype(str)

# 4. 문자 넣어주기
arr3[idx_3] = 'fiz'
arr3[idx_5] = 'buz'
arr3[idx_15] = 'fbz'

In [29]:
arr3

array([['118', '106', 'fiz', 'buz', '104', 'buz', 'buz', 'fiz'],
       ['122', 'fiz', 'buz', '127', '101', 'fiz', '104', '121'],
       ['fiz', 'fiz', 'buz', 'fiz', '106', '101', 'buz', '124'],
       ['101', 'fiz', 'fiz', '119', '121', '128', 'fiz', '106'],
       ['109', 'fiz', '118', 'buz', '119', '104', '127', '119'],
       ['119', 'fiz', 'fiz', '101', 'fiz', '104', '122', 'fiz'],
       ['fiz', '112', '106', '113', 'fiz', 'fiz', '107', '113'],
       ['fiz', 'fbz', '109', '112', 'fiz', '109', 'buz', 'buz']],
      dtype='<U21')

In [7]:
a = range(1,4)
type(

range

# 복습

- 강의용 교안 보면서 복습
- 진도는 그냥 평소하던것처럼 타이핑하면서 새로 치기
- 오늘은 클래스 교안부터 끝까지 쭉 복습하자

In [ ]:
# 데코레이터 복습
# test1,2,3 는 숫자 2개를 입력받아 그 사이의 숫자를 sum하는 함수. 하나는 for-loop이용. 다른 하나는 reduce함수 이용, 다른 하나는 sum함수 이용

In [55]:
import time
# 데코레이터
def count_time(func):
    
    def wrapper(*args,**kwargs):
        start = time.time()
        result = func(*args,**kwargs)
        end = time.time()
        print("소요시간 : {}".format(end-start))
        return result
        
    return wrapper

In [56]:
#for loop 활용
@count_time
def test1(num1,num2):
    
    result = 0
    for i in range(num1,num2+1):
        result += i
    return result    

In [57]:
#sum 함수 활용 -> sum함수가 제일 빠르다.
@count_time
def test2(num1,num2):
    
    data = range(num1,num2+1)
    return sum(data)

In [58]:
from functools import reduce
#reduce 활용
@count_time
def test3(num1,num2):
    
    result = reduce(lambda x,y:x+y,range(num1,num2+1))
    return result

In [59]:
test1(1,100000)

소요시간 : 0.0071680545806884766


5000050000

In [60]:
test2(1,100000)

소요시간 : 0.002065896987915039


5000050000

In [61]:
test3(1,100000)

소요시간 : 0.01120305061340332


5000050000

In [71]:
# 데코레이터 복습
# 문제 : 패스워드가 맞아야 함수가 실행되도록 하는 데코레이터 작성

data = {'test':'1234','python':'5678'}

def check_pw(func):
    def wrapper(*args,**kwargs):
        
        user_id = input('아이디를 입력하세요 :')
        user_pw = input("비밀번호를 입력하세요 : ")
        if user_id in data:
            if user_pw in data[user_id]:
                return func(*args,**kwargs)
            
        return '잘못 입력하셨습니다.'
    return wrapper

In [72]:
@check_pw
def plus(a,b):
    return a+b

In [101]:
class Calculator:
    def __init__(self,num1,num2):
        self.num1 = num1
        self.num2 = num2
        
    def plus(self):
        return self.num1 + self.num2
    
    def __repr__(self):
        return str('num1 : {}, num2 : {} '.format(self.num1,self.num2))
    
    def __str__(self):
        return str(self.num1 * self.num2)

In [102]:
calc = Calculator(10,20)

In [107]:
calc

num1 : 10, num2 : 20 

In [140]:
class Integer:
    def __init__(self,num):
        self.num = num
        
    def __repr__(self):
        return str(self.num)
    
    def __str__(self):
        return str(self.num)
    
    def __add__(self,unit):
        return self.num + unit.num

In [141]:
a = Integer(1)
b = Integer(100)
a

1

In [142]:
print(a)

1


In [143]:
a+b

101

In [145]:
a.__add__(b)

101

In [205]:
#모듈 : py확장자를 가진 파일, 클래스 함수 변수를 모아놓은 것.
#패키지 : 모듈의 모임. 
#디렉토리 - 패키지 / 파일 - 모듈

!ls

0401_practice_Python.ipynb   0407_practice_python_2.ipynb
0402_practice_Python.ipynb   0408_practice_python.ipynb
0403_practice_Python.ipynb   0409_practice_python.ipynb
0405_practice_python.ipynb   __pycache__
0406_practice_python.ipynb   dss.py


In [206]:
%%writefile dss.py
# 모듈 생성

num = 1

class Cal_:
    
    num = 100
    
    def __init__(self):
        self.num1 = num1
        self.num2 = num2
    
    def sum_(self,*args):
        return sum(args)    #*args -> 하나씩 까진 상태 //  args -> 튜플로 묶여있는 상태

Overwriting dss.py


In [207]:
!ls

0401_practice_Python.ipynb   0407_practice_python_2.ipynb
0402_practice_Python.ipynb   0408_practice_python.ipynb
0403_practice_Python.ipynb   0409_practice_python.ipynb
0405_practice_python.ipynb   __pycache__
0406_practice_python.ipynb   dss.py


In [208]:
%whos

Variable   Type      Data/Info
------------------------------
cal_obj    Cal_      <dss.Cal_ object at 0x11a536650>
dss        module    <module 'dss' from '/User<...>ᆼ 연습 노트북/dss.py'>


In [216]:
import dss

In [217]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? 
Nothing done.


In [218]:
import dss

In [219]:
%whos

Variable   Type      Data/Info
------------------------------
cal_obj    Cal_      <dss.Cal_ object at 0x10c0d6e10>
dss        module    <module 'dss' from '/User<...>ᆼ 연습 노트북/dss.py'>


In [220]:
cal_obj = dss.Cal_()    #모듈.클래스명() = obj 생성 -> obj생성했으니 

In [221]:
cal_obj.sum_(1,2,3,4,5)    # obj.func(---)

15

In [ ]:
# 모듈.함수(--)  -> 모듈 내 직속 함수 있을 때
# 모듈.클래스.함수(--)  -> 모듈 내 클래스 속 함수 사용 시
# 모듈.변수     -> 모듈 내 직속 변수 있을 때

In [222]:
import numpy as np

In [225]:
arr = np.random.randint(1,100,9).reshape(3,3)

In [226]:
arr

array([[ 5, 83,  5],
       [14, 45, 36],
       [91,  5, 76]])

In [227]:
arr[1][::-1]

array([36, 45, 14])

In [229]:
arr[arr<=10] = 0

In [230]:
arr

array([[ 0, 83,  0],
       [14, 45, 36],
       [91,  0, 76]])

In [238]:
idx = arr<=40
idx

array([[ True, False,  True],
       [ True, False,  True],
       [False,  True, False]])

In [240]:
arr2 = arr.astype(str)
arr2[idx] = '40이하'
arr2

array([['40이하', '83', '40이하'],
       ['40이하', '45', '40이하'],
       ['91', '40이하', '76']], dtype='<U21')

In [242]:
idx = arr>5
idx

array([[False,  True, False],
       [ True,  True,  True],
       [ True, False,  True]])

In [251]:
import random
arr = random.randint(1,10)
arr

arr2 = np.random.randint(1,6,6)
arr2

array([5, 1, 3, 5, 1, 4])

In [258]:
dice = []

while True:
    
    arr = random.randint(1,10)
    if len(dice) == 6:
        break
    if arr not in dice:
        dice.append(arr)

dice

[4, 8, 1, 6, 9, 3]

In [266]:
# linspace, logspace

arr = np.linspace(1,100,4)
arr

np.logspace(10,100,4)

array([1.e+010, 1.e+040, 1.e+070, 1.e+100])

In [267]:
# 30세에 연봉이 $100000 이고 60세의 연봉이 $1000000 일때
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세, 50세 연봉을 출력

In [273]:
arr = np.linspace(100000,1000000,4)
arr2 = np.logspace(np.log10(100000),np.log10(1000000),4)
print(arr)
print(arr2)

[ 100000.  400000.  700000. 1000000.]
[ 100000.          215443.46900319  464158.88336128 1000000.        ]


In [278]:
np.log10(1000000)

6.0

In [279]:
np.logspace(5,6,4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

In [284]:
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(2,3))
arr3 = np.random.randint(1,10,(3,2))

print(arr1,arr2,arr3,sep='\n')

[[7 6 1]
 [3 7 9]
 [4 3 6]]
[[5 7 4]
 [1 7 8]]
[[9 3]
 [2 5]
 [7 1]]


In [285]:
#행렬 데이터 결합 : concatenate

# 세로 결합 : 열의 차원이 같아야 결합 가능

In [292]:
np.concatenate((arr1,arr2))

array([[7, 6, 1],
       [3, 7, 9],
       [4, 3, 6],
       [5, 7, 4],
       [1, 7, 8]])

In [293]:
# 가로 결합 : 행의 차원이 같아야 결합 가능

In [295]:
np.concatenate((arr1,arr3),axis=1)

array([[7, 6, 1, 9, 3],
       [3, 7, 9, 2, 5],
       [4, 3, 6, 7, 1]])

In [296]:
import re

In [299]:
data = 'fast campus fast'
re.findall('fast',data)

['fast', 'fast']

In [300]:
re.sub('fast','slow',data)

'slow campus slow'

In [3]:
import numpy as np
import pandas as pd

# 시리즈
- 동일한 데이터 타입의 값을 갖는다

In [5]:
# 시리즈

a = pd.Series(np.random.randint(10,size=5))
a

0    5
1    9
2    9
3    3
4    0
dtype: int64

In [7]:
# index 설정

data = pd.Series(np.random.randint(10,size=5),index=list('ABCDE'))
data

A    8
B    9
C    3
D    8
E    8
dtype: int64

In [10]:
data.index, data.values

(Index(['A', 'B', 'C', 'D', 'E'], dtype='object'), array([8, 9, 3, 8, 8]))

In [11]:
data['B']

9

In [12]:
data.B

9

In [13]:
data.B = 10

In [14]:
data

A     8
B    10
C     3
D     8
E     8
dtype: int64

In [15]:
data['B'] = 11

In [16]:
data

A     8
B    11
C     3
D     8
E     8
dtype: int64

In [20]:
data = 10
data = pd.Series(np.random.randint(5,size=5),index=list('ABCDE'))
data

A    2
B    3
C    3
D    4
E    3
dtype: int64

In [29]:
#판다스도 넘파이처럼 브로드캐스팅 가능
data*10

A    20
B    30
C    30
D    40
E    30
dtype: int64

In [30]:
#판다스도 넘파이처럼 offset index 가능

In [35]:
data[::-1]

E    3
D    4
C    3
B    3
A    2
dtype: int64

In [38]:
#시리즈 넣어줄 때, 딕셔너리로 넣어줌
data2 = pd.Series({'D':3,'E':4,'F':5})
data2

D    3
E    4
F    5
dtype: int64

In [39]:
data, data2

(A    2
 B    3
 C    3
 D    4
 E    3
 dtype: int64, D    3
 E    4
 F    5
 dtype: int64)

In [42]:
# 더해주는 건, 같은 인덱스끼리만 더해준다
data+data2

A    NaN
B    NaN
C    NaN
D    7.0
E    7.0
F    NaN
dtype: float64

In [43]:
result = data+data2
result

A    NaN
B    NaN
C    NaN
D    7.0
E    7.0
F    NaN
dtype: float64

In [45]:
result.isnull()

A     True
B     True
C     True
D    False
E    False
F     True
dtype: bool

In [46]:
result[result.isnull()]=data

In [47]:
result

A    2.0
B    3.0
C    3.0
D    7.0
E    7.0
F    NaN
dtype: float64

In [48]:
result[result.isnull()]=data2

In [49]:
result

A    2.0
B    3.0
C    3.0
D    7.0
E    7.0
F    5.0
dtype: float64

In [136]:
data

A    2
B    3
C    3
D    4
E    3
dtype: int64

In [137]:
data['A']

2

In [140]:
data_ = pd.Series([1,2,3,4,5,6],index=list("ABCDEF"))
data_
data_ = pd.Series({'G':7,'H':8})
data_

G    7
H    8
dtype: int64

# Dataframe

- 여러개의 시리즈로 구성
- 같은 컬럼에 있는 value값은 같은 데이터 타입을 갖는다.

In [110]:
# 데이터 프레임 생성1 : 딕셔너리의 리스트
# 딕셔너리 키 = 컬럼이름 / 딕셔너리 데이터 = 데이터
# { colum1 set, colum2 set, ... }

datas = {
    'name':['dss','camp'],
    'email':['dss@emaitl.com','fcamp@dmail.com']    
}
datas

{'name': ['dss', 'camp'], 'email': ['dss@emaitl.com', 'fcamp@dmail.com']}

In [111]:
# 데이터 프레임 생성2 : 리스트의 딕셔너리
# row로 채워줌. 역시나 key가 컬럼이름. value가 값.
# key : value, key : value 이렇게 set로 한줄 한줄 쳐주는 것
# [ {row1 set}, {row2 set}, ... ]

datas = [
    {'name':'dss','email':'dss@gmail.com'},
    {'name':'fcamp','email':'fcamp@dss.net'}
]

datas

[{'name': 'dss', 'email': 'dss@gmail.com'},
 {'name': 'fcamp', 'email': 'fcamp@dss.net'}]

In [112]:
df = pd.DataFrame(datas)
df

name          email
0    dss  dss@gmail.com
1  fcamp  fcamp@dss.net

In [113]:
# 인덱스를 추가하는 방법

df = pd.DataFrame(datas, index=['one','two'])
df

name          email
one    dss  dss@gmail.com
two  fcamp  fcamp@dss.net

In [114]:
df.columns

Index(['name', 'email'], dtype='object')

In [115]:
df.values

array([['dss', 'dss@gmail.com'],
       ['fcamp', 'fcamp@dss.net']], dtype=object)

In [116]:
df.index

Index(['one', 'two'], dtype='object')

In [117]:
# 데이터 프레임에서 데이터의 선택 : row, column, (row,column)
df

name          email
one    dss  dss@gmail.com
two  fcamp  fcamp@dss.net

In [118]:
# row를 선택해도 시리즈 데이터가 됨. -> 마스킹 가능
df.loc['one']

name               dss
email    dss@gmail.com
Name: one, dtype: object

In [119]:
df.loc['one']['email']

'dss@gmail.com'

In [120]:
 # row 데이터 추가하고 싶다. row는 리스트의 딕셔너리로 넣어준다.(하나니까 그냥 딕셔너리로))
df.loc['three'] = {'name':'kjs','email':'kjscop@naver.com'}
df    

name             email
one      dss     dss@gmail.com
two    fcamp     fcamp@dss.net
three    kjs  kjscop@naver.com

In [121]:
# column 선택

In [122]:
df['name']

one        dss
two      fcamp
three      kjs
Name: name, dtype: object

In [123]:
# column 생성
df['id'] = ""
df

name             email id
one      dss     dss@gmail.com   
two    fcamp     fcamp@dss.net   
three    kjs  kjscop@naver.com

In [124]:
# row 생성 - 빈칸
df.loc['four'] = ''

In [125]:
df

name             email id
one      dss     dss@gmail.com   
two    fcamp     fcamp@dss.net   
three    kjs  kjscop@naver.com   
four

In [126]:
# row 생성 - 찬 칸
df.loc['five'] = {'name':'kjscop','email':'kjscop@naver.com','id':'abc'}
df

name             email   id
one       dss     dss@gmail.com     
two     fcamp     fcamp@dss.net     
three     kjs  kjscop@naver.com     
four                                
five   kjscop  kjscop@naver.com  abc

In [129]:
df['id'] = {'a','b','c','d','e'}
df

name             email id
one       dss     dss@gmail.com  a
two     fcamp     fcamp@dss.net  d
three     kjs  kjscop@naver.com  b
four                             c
five   kjscop  kjscop@naver.com  e

In [130]:
# row, column 선택

In [133]:
df.loc[['one','two'],['email','name']]

email   name
one  dss@gmail.com    dss
two  fcamp@dss.net  fcamp

In [134]:
df.head()

name             email id
one       dss     dss@gmail.com  a
two     fcamp     fcamp@dss.net  d
three     kjs  kjscop@naver.com  b
four                             c
five   kjscop  kjscop@naver.com  e

In [135]:
df.tail()

name             email id
one       dss     dss@gmail.com  a
two     fcamp     fcamp@dss.net  d
three     kjs  kjscop@naver.com  b
four                             c
five   kjscop  kjscop@naver.com  e

# Pandas 의 여러 함수들

# 1. apply

In [141]:
# apply 함수
# map 과 유사

# email컬럼에서 메일의 도메인만 가져와서 새로운 domain 컬럼을 생성
df

name             email id
one       dss     dss@gmail.com  a
two     fcamp     fcamp@dss.net  d
three     kjs  kjscop@naver.com  b
four                             c
five   kjscop  kjscop@naver.com  e

In [152]:
def domain(email):
    return email.split('@')[1].split('.')[0]

domain(df.loc['one']['email'])

'gmail'

In [154]:
df['email']['four'] = 'kjsocp@nameil.com'
df['domain'] = df['email'].apply(domain)

In [155]:
df

name              email id  domain
one       dss      dss@gmail.com  a   gmail
two     fcamp      fcamp@dss.net  d     dss
three     kjs   kjscop@naver.com  b   naver
four           kjsocp@nameil.com  c  nameil
five   kjscop   kjscop@naver.com  e   naver

In [157]:
import makedata

ModuleNotFoundError: No module named 'makedata'

In [159]:
%%writefile makedata.py


# 사람의 이름과 나이가 들어간 데이터를 만듭니다.
import random
import numpy as np

# 랜덤한 이름 출력하는 함수
def get_name():
    names = ["Adam", "Alan", "Alex", "Alvin", "Andrew",
             "Anthony", "Arnold", "Jin", "Billy", "Anchal"]
    return random.choice(names)

# 랜덤한 나이 출력
def get_age(start=20, end=40):
    return np.random.randint(start, end + 1)

# 랜덤하게 나이와 이름을 출력
def make_data(rows=10):
    datas = []
    for _ in range(rows):
        data = {"Age": get_age(), "Name": get_name()}
        datas.append(data)
    return datas

Writing makedata.py


In [162]:
from makedata import *

In [163]:
get_name()

'Alvin'

In [164]:
get_age()

35

In [183]:
make_data(5)

[{'Age': 29, 'Name': 'Arnold'},
 {'Age': 24, 'Name': 'Alvin'},
 {'Age': 34, 'Name': 'Arnold'},
 {'Age': 31, 'Name': 'Jin'},
 {'Age': 22, 'Name': 'Arnold'}]

In [184]:
df1 = pd.DataFrame(make_data(5))
df2 = pd.DataFrame(make_data(5))

In [185]:
df2

Age     Name
0   37   Andrew
1   30      Jin
2   23  Anthony
3   27    Billy
4   30      Jin

# 2. append
- 데이터를 밑에다가 추가로 넣을 때, 연결할 떄 사용

In [195]:
# dataframe 합치기

df3 = df1.append(df2)
df3

Age     Name
0   32      Jin
1   32    Alvin
2   36  Anthony
3   32     Adam
4   38   Anchal
0   37   Andrew
1   30      Jin
2   23  Anthony
3   27    Billy
4   30      Jin

In [196]:
df3[2:7]

Age     Name
2   36  Anthony
3   32     Adam
4   38   Anchal
0   37   Andrew
1   30      Jin

In [197]:
# 인덱스 재정렬

df3

Age     Name
0   32      Jin
1   32    Alvin
2   36  Anthony
3   32     Adam
4   38   Anchal
0   37   Andrew
1   30      Jin
2   23  Anthony
3   27    Billy
4   30      Jin

# 3. reset_index

In [198]:
# reset_index
# drop=True <= index 2줄생긴 것 한 줄로
# inplace=True  <= 인덱스 리셋 결과 저장
df3.reset_index(drop=True)

Age     Name
0   32      Jin
1   32    Alvin
2   36  Anthony
3   32     Adam
4   38   Anchal
5   37   Andrew
6   30      Jin
7   23  Anthony
8   27    Billy
9   30      Jin

In [199]:
df3.reset_index(drop=True,inplace=True)
df3.tail(2)

Age   Name
8   27  Billy
9   30    Jin

# 4. concat
- row나 column으로 데프 합칠 때 사용

In [200]:
df1

Age     Name
0   32      Jin
1   32    Alvin
2   36  Anthony
3   32     Adam
4   38   Anchal

In [201]:
df2

Age     Name
0   37   Andrew
1   30      Jin
2   23  Anthony
3   27    Billy
4   30      Jin

In [205]:
df3 = pd.concat([df1,df2]).reset_index(drop=True)
df3.tail(2)

Age   Name
8   27  Billy
9   30    Jin

In [206]:
# 가로로 합치기
pd.concat([df3,df1],axis=1)

Age     Name   Age     Name
0   32      Jin  32.0      Jin
1   32    Alvin  32.0    Alvin
2   36  Anthony  36.0  Anthony
3   32     Adam  32.0     Adam
4   38   Anchal  38.0   Anchal
5   37   Andrew   NaN      NaN
6   30      Jin   NaN      NaN
7   23  Anthony   NaN      NaN
8   27    Billy   NaN      NaN
9   30      Jin   NaN      NaN

In [207]:
# concat 합칠 때 주의사항
# 1. axis = 1 가로로 합침
# 2. join = 'inner' 교집합만 출력!

In [208]:
pd.concat([df3,df1],axis=1,join='inner')

Age     Name  Age     Name
0   32      Jin   32      Jin
1   32    Alvin   32    Alvin
2   36  Anthony   36  Anthony
3   32     Adam   32     Adam
4   38   Anchal   38   Anchal

# 5. groupby
- 특정 컬럼의 중복되는 데이터를 합쳐서 새로운 데이터 프레임을 만드는 방법

In [209]:
df = pd.DataFrame(make_data())
df
# 중복되는 데이터가 있음

Age     Name
0   32    Alvin
1   32    Billy
2   22   Anchal
3   29     Alan
4   35   Anchal
5   34      Jin
6   37   Arnold
7   36      Jin
8   21  Anthony
9   27     Alex

### size 

In [210]:
# groupby 의 size 라는 함수를 이용

In [242]:
df.groupby('Name').size()

Name
Alan       1
Alex       1
Alvin      1
Anchal     2
Anthony    1
Arnold     1
Billy      1
Jin        2
dtype: int64

In [243]:
# 위의 시리즈 타입이 아닌, 데프로 변환

In [245]:
result = df.groupby('Name').size().reset_index(name='count')
result

Name  count
0     Alan      1
1     Alex      1
2    Alvin      1
3   Anchal      2
4  Anthony      1
5   Arnold      1
6    Billy      1
7      Jin      2

### sort_values : 설정한 컬럼으로 데이터프레임을 정렬

In [230]:
result.sort_values(['count'],inplace=True)

In [236]:
result.reset_index(drop=True,inplace=True)

In [237]:
result

Name  count
0     Alan      1
1     Alex      1
2    Alvin      1
3  Anthony      1
4   Arnold      1
5    Billy      1
6   Anchal      2
7      Jin      2

### agg 
- aggregation 함수

In [238]:
df.groupby('Name').agg('min').reset_index()

Name  Age
0     Alan   29
1     Alex   27
2    Alvin   32
3   Anchal   22
4  Anthony   21
5   Arnold   37
6    Billy   32
7      Jin   34

In [239]:
# groupby 해주는 방법은 크게 2가지
# 1. agg 함수 적용
# 2. size min max 같은 것 써서 시리즈 형태로 정렬을 해주는 것

In [240]:
df.describe()

Age
count  10.000000
mean   30.500000
std     5.642104
min    21.000000
25%    27.500000
50%    32.000000
75%    34.750000
max    37.000000

# 6. merge 함수 = sql(join)

- 2개 이상의 데프를 합쳐서 결과 출력