```
t = torch.FlaotTensor( ndarray )

t.dim()
t.shape
t.size()

1. Broadcasting ==> 사이즈도 변환해서 boradcasting 연산 해줌 ( 2x1 + 1x2 ==>> 2x2 + 2x2로 '변형 후 연산' )
2. .matmul / .mul
3. .mean(), .mean( ,dim=0) 0차원(행)으로 mean값을 표현해라(행으로 표시)
4. .sum(), .sum( ,dim=0) 0차원(행)으로 sum값을 표현해라(행으로 표시)
5. .max(), .max( ,dim=0) 0차원(행)으로 훑으며 각 행의 최대값을 표현해라
6. .view([1,-1]) == reshape([1,-1])
7. .squeeze([-1,3,1]), .unsqueeze([-1,1]) 차원 추가 / 제거
8. .float(), .long(), ... type casting
9. .cat(), .cat( ,dim=1) 1차원(열)로 cat 연결해라 
10. .stack(), .stack( ,dim=1) 1차원(열)로 붙여라 ==> .stack() = .view() + .cat() 
11. .ones_like(t), .zeros_like(t) t텐서의 사이즈로 1 또는 0으로 채운 텐서 생성
12. inplace opreation ==> .mul() -> .mul_()
```

## Tensor만들기
- [1,2,3] 을 만들고, np.array 로 감싸면 끝

### 1. 1-D Tensor with numpy

In [1]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a = [a for a in range(1,10+1)]
t = np.array(a)

In [8]:
print('dim of t: ', t.ndim)
print('Shape of t: ', t.shape)

dim of t:  2
Shape of t:  (4, 3)


**Tensor의 크기 표현**
- 2 x 3 = (2,3)
- (10,) = 1 x 10 = (1,10)

### 2. 2-D Tensor with numpy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [7]:
print('dim of t: ', t.ndim)
print('Shape of t: ', t.shape)

dim of t:  2
Shape of t:  (4, 3)


### 3. Pytorch Tensor Allocation

In [9]:
import torch

### 3-1) 1D tensor with torch

In [10]:
t = torch.FloatTensor([a for a in range(0,7+0)])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [15]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [18]:
t[-1], t[2:5]

(tensor(6.), tensor([2., 3., 4.]))

### 3-2) 2D tensor with torch

In [19]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [21]:
print(t.shape, t.dim())

torch.Size([4, 3]) 2


In [22]:
t[:,1]

tensor([ 2.,  5.,  8., 11.])

In [23]:
t[2,:]

tensor([7., 8., 9.])

In [28]:
t[:,:2]

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

In [29]:
t[:,:-1]

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

### 3-3) Broadcasting

In [30]:
m1 = torch.FloatTensor([[2,2]])
m2 = torch.FloatTensor([[3,3]])
m1+m2

tensor([[5., 5.]])

In [31]:
m3 = torch.FloatTensor([3])
m3

tensor([3.])

In [32]:
m1+m3

tensor([[5., 5.]])

In [35]:
print(m1.size(),m3.size())

torch.Size([1, 2]) torch.Size([1])


In [36]:
m4 = torch.FloatTensor([[3],[4]])
m4

tensor([[3.],
        [4.]])

In [37]:
print(m1.size(),m4.size())

torch.Size([1, 2]) torch.Size([2, 1])


In [38]:
m1

tensor([[2., 2.]])

**torch에서는 벡터의 shape이 서로 달라도, shape을 변형해 연산을 시켜줌**
```

아래와 같은 경우,

m1을
[[2,2],
 [2,2]]
m4를
[[3,3],
 [4,4]]

로 변형해 m1 + m4를 연산한 것.

차후 주의해야 함

```

In [39]:
m1+m4

tensor([[5., 5.],
        [6., 6.]])

### 3-4) 행렬곱 / 곱셈의 차이
- 행렬곱 : .matmul
- 곱 : .mul -> element-wise 연산

In [43]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.shape,m2.shape)

torch.Size([2, 2]) torch.Size([2, 1])


In [45]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [46]:
m2

tensor([[1.],
        [2.]])

In [44]:
m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [48]:
# shape 문제 발생(.matmul은 대수학적 행렬곱 실행한다는 것)
m2.matmul(m1)

RuntimeError: size mismatch, m1: [2 x 1], m2: [2 x 2] at ../aten/src/TH/generic/THTensorMath.cpp:136

In [49]:
m1.mul(m2)

tensor([[1., 2.],
        [6., 8.]])

In [50]:
m2.mul(m1)

tensor([[1., 2.],
        [6., 8.]])

### 3-5) 평균
- Numpy와 유사. 내부 element의 mean값을 스칼라로 반환

- torch.mean(m1)
- torch.mean(m1,dim=0)

    - *행렬에서 첫 차원은 행, 두번째 차원은 열이다*
    - *즉, torch.mean(m1,dim=0)은 행렬에서 행의 차원을 제거하겠다. 평균값으로*
    - *2x2 -> 1x2로

In [51]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [63]:
torch.mean(m1)

tensor(2.5000)

In [60]:
torch.mean(m1,dim=0)

tensor([2., 3.])

In [58]:
torch.mean(m1,dim=1)

tensor([1.5000, 3.5000])

### 3-6) SUM
- Numpy와 유사. 내부 element의 sum값을 스칼라로 반환

- torch.sum(m1)
- torch.sum(m1,dim=0)

    - *행렬에서 첫 차원은 행, 두번째 차원은 열이다*
    - *즉, torch.sum(m1,dim=0)은 행렬에서 행의 차원을 제거하겠다. 합계로*
    - *2x2 -> 1x2로

In [64]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [66]:
torch.sum(m1)

tensor(10.)

In [67]:
torch.sum(m1,dim=0)

tensor([4., 6.])

In [68]:
torch.sum(m1,dim=1)

tensor([3., 7.])

### 3-7) max, argmax

- max : 최대값 리턴

- argmax : 최대값의 인덱스 리턴


In [69]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [70]:
torch.max(m1)

tensor(4.)

In [71]:
torch.argmax(m1)

tensor(3)

In [72]:
torch.max(m1,dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [73]:
torch.max(m1,dim=1)

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

In [75]:
m2 = torch.FloatTensor([[1,10],[7,4]])
m2

tensor([[ 1., 10.],
        [ 7.,  4.]])

In [76]:
torch.max(m2)

tensor(10.)

In [77]:
torch.max(m2,dim=0)

torch.return_types.max(
values=tensor([ 7., 10.]),
indices=tensor([1, 0]))

In [78]:
torch.max(m2,dim=1)

torch.return_types.max(
values=tensor([10.,  7.]),
indices=tensor([1, 0]))

In [80]:
torch.max(m2,dim=1)[0]

tensor([10.,  7.])

In [82]:
torch.max(m2,dim=1)[1]

tensor([1, 0])

### 3-8) View

- 원소의 수를 유지하며, 텐서의 크기 변경 (numpy의 reshape 역할)

In [87]:
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [88]:
ft3 = torch.FloatTensor(t)
ft3

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [89]:
print(ft3.shape)

torch.Size([2, 2, 3])


**3차원에서 2차원 텐서로 변경**

In [91]:
ft2 = ft3.view([-1,3])
ft2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [92]:
print(ft2.shape)

torch.Size([4, 3])


**3차원은 유지하되, shape만 변경**

In [93]:
ft_ = ft3.view([-1,1,3])
ft_

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [94]:
ft_.shape

torch.Size([4, 1, 3])

### 3-9) squeeze

- 1인 차원을 제거함
- ex) (3,1) ==> (3,)

In [96]:
t = torch.FloatTensor([[1],[2],[3]])

tensor([[1.],
        [2.],
        [3.]])

In [101]:
print(t,t.shape)

tensor([[1.],
        [2.],
        [3.]]) torch.Size([3, 1])


In [99]:
t2 = t.squeeze()

In [100]:
print(t2, t2.shape)

tensor([1., 2., 3.]) torch.Size([3])


### 3-10) unsqueeze

- 1인 차원을 추가함
- ex) (3,) ==> (3,1)

- view로도 구현 가능

In [102]:
t = torch.FloatTensor([0,1,2])
print(t,t.shape)

tensor([0., 1., 2.]) torch.Size([3])


In [103]:
t2 = t.unsqueeze(0)
print(t2,t2.shape)

tensor([[0., 1., 2.]]) torch.Size([1, 3])


In [104]:
t3 = t.unsqueeze(-1)
print(t3,t3.shape)

tensor([[0.],
        [1.],
        [2.]]) torch.Size([3, 1])


In [105]:
t2_ = t.view([1,-1])
print(t2_,t2_.shape)

tensor([[0., 1., 2.]]) torch.Size([1, 3])


In [106]:
t3_ = t.view([-1,1])
print(t3_,t3_.shape)

tensor([[0.],
        [1.],
        [2.]]) torch.Size([3, 1])


### 3-11) type casting

- cpu / gpu, 64bit/32bit 등에 따른 각각의 자료형이 torch에는 존재함
- 이러한 자료형을 변환해주는 것을 type casting이라 함
```
.float() : float타입으로 변환
.long() : long타입으로 변환
.byte() : byte타입으로 변환
etc...
```

In [116]:
lt = torch.LongTensor([1,2,3,4])
print(lt,lt.shape)

tensor([1, 2, 3, 4]) torch.Size([4])


In [117]:
lt_float = lt.float()
print(lt_float,lt_float.shape)

tensor([1., 2., 3., 4.]) torch.Size([4])


In [118]:
bt = torch.ByteTensor([1,2,3,4])
print(bt,bt.shape)

tensor([1, 2, 3, 4], dtype=torch.uint8) torch.Size([4])


In [120]:
bt.dtype

torch.uint8

In [122]:
bt.long().dtype

torch.int64

In [123]:
bt.float().dtype

torch.float32

### 3-12) concatenate (연결하기)

- dim = 0 ---> 0 dim(행)을 늘려라(연결해라)

In [126]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(x,y,sep='\n')

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [130]:
torch.cat([x,y],dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [131]:
torch.cat([x,y],dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

### 3-13) stacking

- dim=0 / dim=1 에 따라 쌓는 것

- stack연산은 생각보다 많은 연산을 알아서 해준다.
- 여기에선, (2,) --> (2,1)로 view/unsqueeze연산 후 cat연산도 함께 해준 것을 알 수 있다.
```
stack = view/sque/unsque + cat 연산임을 알 수 있다.
```

In [137]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [138]:
torch.stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [139]:
torch.stack([x,y,z],dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [140]:
torch.stack([x,y,z],dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 3-14) ones_like, zeros_like 연산

- 1로 채워진 텐서 생성 : ones_like
- 0으로 채워진 텐서 생성 : zeros_like

In [141]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
print(x,x.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])


In [142]:
x1 = torch.ones_like(x)
print(x1,x1.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])


In [143]:
x2 = torch.zeros_like(x)
print(x2,x2.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.Size([2, 3])


### 3-15) inpace operation

- 끝에 ' _ ' 붙이면 됨

In [145]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
print(x,x.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])


In [150]:
x.mul(2)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [147]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [152]:
x.mul_(2)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [153]:
x

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])