# 1. 역행렬 계산

In [1]:
import numpy as np

A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [3]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [6]:
A @ Ainv == np.eye(3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 2. 역행렬과 선형 연립방정식의 해

In [7]:
b = np.array([[2], [2], [3]])
b

array([[2],
       [2],
       [3]])

In [8]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [10]:
A @ x == b

array([[ True],
       [ True],
       [ True]])

# 3. Least square problem

- 선형연립방정식 및 최소제곱법 문제 풀 때, np.linalg.lstsq(A,b) 활용!
- lstsq()
- pseudo inverse 계산해 해 찾기 = lsqst()

In [27]:
x, resid, rank, s = np.linalg.lstsq(A, b)
print(x, resid, rank, s, sep='\n\n')

# x = 해답
# resid = RSS(잔차제곱합)
# rank = 행렬 A의 랭크
# s = 특잇값

[[1.]
 [1.]
 [1.]]

[]

3

[2.41421356 1.         0.41421356]


# 4. 보스턴 집값 예측 문제 - 가중치 벡터 계산 (Least square problem)

In [28]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [29]:
w, resid, rank, s = np.linalg.lstsq(X,y)

In [31]:
# w를 통해 집값 데이터 X의 각 컬럼별(특징별) 집값과의 비례관계를 유추할 수 있다.
print(w, resid, rank, s, sep='\n\n')

[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00
 -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01
  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02
 -4.16304471e-01]

[12228.04626104]

13

[1.25851816e+04 3.44597406e+03 6.45757109e+02 4.02050461e+02
 1.58964612e+02 1.21502936e+02 9.04652420e+01 7.79311708e+01
 6.50828345e+01 2.46251803e+01 1.80945451e+01 5.51505065e+00
 1.48096916e+00]
