# 박두진 강사님 강의 _ 2일차

### 다중 상속 상세

In [18]:
class A:
    def __init__(self,data="A_data"):
        print("A : __init__",data)
    def method(self):
        print("A : method")

In [19]:
class B:
    def __init__(self,data="B_data"):
        print("B : __init__",data)
    def method(self):
        print("B : method")

In [20]:
# B -> A -> C
class C(A, B):
    def __init__(self):
        super().__init__()
        print("C : __init__")

In [21]:
c = C()

A : __init__ A_data
C : __init__


In [22]:
# A -> B-> C
class C(B, A):
    def __init__(self):
        super().__init__()
        print("C : __init__")
        
c = C()

B : __init__ B_data
C : __init__


### 선택적으로 부모 클래스의 함수 실행

In [23]:
# A -> B-> C
class C(B, A):
    def __init__(self):
        super(C,self).__init__()
        super(B,self).__init__()
        super(B,self).method()    #A에 대한 메소드가 실행됨 (A가 상속되어 오버라이딩 된 B의 method가 아닌...)    
        print("C : __init__")
        
c = C()

B : __init__ B_data
A : __init__ A_data
A : method
C : __init__


### super를 쓰면 다이아몬드 상속 문제를 피할 수 있다. (중복 상속되는..)

### Numpy, Pandas 리뷰

### - pandas가 numpy를 사용해서 속도가 빠름.
### - numpy는 c, c++, 포트란으로 만들어짐
### - 파이썬의 느린 속도를 개선하기 위한 것이 numpy
### - Linear algebra 계산에 주료 사용 : 스칼라, 벡터, 매트릭스
### - index
    ### - ndarray 객체 생성
    ### - 데이터 선택
    ### - 데이터 수정
    ### - 데이터 연산
    ### - ndarray 함수 사용
    ### 크게 보면, 이렇게 나눠서 공부하면 됨

In [27]:
#ndarray 객체 생성
import numpy as np

In [36]:
### 1. 데이터 생성

In [37]:
#ndarray 연산은 ndarray 데이터 타입끼리만 가능
arr1 = np.array([1,2,3])
type(arr1),arr1.dtype

(numpy.ndarray, dtype('int64'))

In [38]:
# 데이터 타입 변경
arr2 = arr1.astype(np.float64)
arr2

array([1., 2., 3.])

In [39]:
### 2. 데이터 선택

In [40]:
arr = np.random.randint(5,size=(3,3))
arr

array([[4, 2, 0],
       [4, 2, 4],
       [3, 1, 2]])

In [42]:
arr[1][2], arr[1,2]   #하지만, 미세한 차이가 있음. 

(4, 4)

In [43]:
# 미세한 차이, arr[1]을 찾고 [2]를 찾는 것 <--> arr[1,2]를 한번에 찾는 것

arr[1:][1:], arr[1:,1:]

(array([[3, 1, 2]]), array([[2, 4],
        [1, 2]]))

In [33]:
### 3. 데이터 수정

In [44]:
arr

array([[4, 2, 0],
       [4, 2, 4],
       [3, 1, 2]])

In [48]:
# 브로드캐스팅. 벡터 = 스칼라.. 스칼라가 벡터 전체에 뿌려짐
arr[1] = 10
arr

array([[ 4,  2,  0],
       [10, 10, 10],
       [ 3,  1,  2]])

In [51]:
arr > 3

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [34]:
### 4. 데이터 연산

In [52]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1 + arr2

array([5, 7, 9])

In [53]:
# any(or), all(and)
arr3 = np.array([2,1,3])
arr1 == arr3

array([False, False,  True])

In [55]:
np.any(arr1 == arr3), np.all(arr1 == arr3)

(True, True)

### 5. ndarray 함수 사용

- sum, mean, median, var, str, min, max
- unique, split, sort, concatenate, 

# quiz
- 60~ 100까지 10점 단위로 10*5 행렬을 생성
- 평균이 80점 이상인 row 데이터를 출력하는 코드를 작성

In [57]:
# 1. 10*5 행렬 생성
datas = np.random.randint(6,11,(10,5))
datas = datas*10
datas

array([[ 70, 100,  90,  70,  70],
       [ 90, 100,  60, 100,  60],
       [ 70,  80,  90,  90,  70],
       [100,  90,  80,  70,  80],
       [ 60,  80,  90,  90,  70],
       [100,  70,  70,  80, 100],
       [100, 100, 100,  70,  80],
       [ 80, 100,  70,  60,  90],
       [ 70,  60, 100,  60,  60],
       [100,  80,  70,  90, 100]])

In [59]:
#2. row별 평균 데이터 구하기
avg_data = np.sum(datas, axis=1) / datas.shape[1]  # shape로 나눠주면, 과목이 추가되거나 컬럼수가 변해도 안바꿔줘도 됨
avg_data

array([80., 82., 80., 84., 78., 84., 90., 80., 70., 88.])

In [60]:
#3. 80점이 넘는 데이터만 출력
datas[avg_data >= 80]

array([[ 70, 100,  90,  70,  70],
       [ 90, 100,  60, 100,  60],
       [ 70,  80,  90,  90,  70],
       [100,  90,  80,  70,  80],
       [100,  70,  70,  80, 100],
       [100, 100, 100,  70,  80],
       [ 80, 100,  70,  60,  90],
       [100,  80,  70,  90, 100]])

In [61]:
#4. 원래 데이터에서 총점하고 평균을 추가 - column에 추가
total = np.sum(datas,axis=1)
total, avg_data

(array([400, 410, 400, 420, 390, 420, 450, 400, 350, 440]),
 array([80., 82., 80., 84., 78., 84., 90., 80., 70., 88.]))

In [62]:
#5. c_ 로도 column 더할 수 있고,
np.c_[datas, total, avg_data]

array([[ 70., 100.,  90.,  70.,  70., 400.,  80.],
       [ 90., 100.,  60., 100.,  60., 410.,  82.],
       [ 70.,  80.,  90.,  90.,  70., 400.,  80.],
       [100.,  90.,  80.,  70.,  80., 420.,  84.],
       [ 60.,  80.,  90.,  90.,  70., 390.,  78.],
       [100.,  70.,  70.,  80., 100., 420.,  84.],
       [100., 100., 100.,  70.,  80., 450.,  90.],
       [ 80., 100.,  70.,  60.,  90., 400.,  80.],
       [ 70.,  60., 100.,  60.,  60., 350.,  70.],
       [100.,  80.,  70.,  90., 100., 440.,  88.]])

In [66]:
#5. append 로도 column 더할 수 있다.
# _c 가 더 좋다.(더 짧고 간결!)
# total.reshape(10,1), avg_Data.reshape(10,1)
result_data = np.append(datas, total.reshape(10,1), axis=1)
result_data = np.append(result_data, avg_data.reshape(10,1), axis=1)
result_data

array([[ 70., 100.,  90.,  70.,  70., 400.,  80.],
       [ 90., 100.,  60., 100.,  60., 410.,  82.],
       [ 70.,  80.,  90.,  90.,  70., 400.,  80.],
       [100.,  90.,  80.,  70.,  80., 420.,  84.],
       [ 60.,  80.,  90.,  90.,  70., 390.,  78.],
       [100.,  70.,  70.,  80., 100., 420.,  84.],
       [100., 100., 100.,  70.,  80., 450.,  90.],
       [ 80., 100.,  70.,  60.,  90., 400.,  80.],
       [ 70.,  60., 100.,  60.,  60., 350.,  70.],
       [100.,  80.,  70.,  90., 100., 440.,  88.]])

In [70]:
import pandas as pd
# 데이터프레임으로 만들기
columns = ['국어','영어','수학','과학','코딩','총점','평균']
point_df = pd.DataFrame(result_data, columns=columns)
point_df

국어     영어     수학     과학     코딩     총점    평균
0   70.0  100.0   90.0   70.0   70.0  400.0  80.0
1   90.0  100.0   60.0  100.0   60.0  410.0  82.0
2   70.0   80.0   90.0   90.0   70.0  400.0  80.0
3  100.0   90.0   80.0   70.0   80.0  420.0  84.0
4   60.0   80.0   90.0   90.0   70.0  390.0  78.0
5  100.0   70.0   70.0   80.0  100.0  420.0  84.0
6  100.0  100.0  100.0   70.0   80.0  450.0  90.0
7   80.0  100.0   70.0   60.0   90.0  400.0  80.0
8   70.0   60.0  100.0   60.0   60.0  350.0  70.0
9  100.0   80.0   70.0   90.0  100.0  440.0  88.0

### pandas
- 데이터 분석을 위한 사용이 쉽고 성능이 좋은 오픈소스 python 라이브러리
- Series, DataFrame


In [71]:
point_df

국어     영어     수학     과학     코딩     총점    평균
0   70.0  100.0   90.0   70.0   70.0  400.0  80.0
1   90.0  100.0   60.0  100.0   60.0  410.0  82.0
2   70.0   80.0   90.0   90.0   70.0  400.0  80.0
3  100.0   90.0   80.0   70.0   80.0  420.0  84.0
4   60.0   80.0   90.0   90.0   70.0  390.0  78.0
5  100.0   70.0   70.0   80.0  100.0  420.0  84.0
6  100.0  100.0  100.0   70.0   80.0  450.0  90.0
7   80.0  100.0   70.0   60.0   90.0  400.0  80.0
8   70.0   60.0  100.0   60.0   60.0  350.0  70.0
9  100.0   80.0   70.0   90.0  100.0  440.0  88.0

In [77]:
# 마지막 row에 과목별 평균 행을 추가
point_df.loc['평균'] = point_df.sum() / len(point_df)
point_df

국어     영어     수학     과학     코딩     총점    평균
0    70.0  100.0   90.0   70.0   70.0  400.0  80.0
1    90.0  100.0   60.0  100.0   60.0  410.0  82.0
2    70.0   80.0   90.0   90.0   70.0  400.0  80.0
3   100.0   90.0   80.0   70.0   80.0  420.0  84.0
4    60.0   80.0   90.0   90.0   70.0  390.0  78.0
5   100.0   70.0   70.0   80.0  100.0  420.0  84.0
6   100.0  100.0  100.0   70.0   80.0  450.0  90.0
7    80.0  100.0   70.0   60.0   90.0  400.0  80.0
8    70.0   60.0  100.0   60.0   60.0  350.0  70.0
9   100.0   80.0   70.0   90.0  100.0  440.0  88.0
평균   84.0   86.0   82.0   78.0   78.0  408.0  81.6

In [81]:
# 평균이 80점 이상이면 pass, 아니면 fail 이 들어가는 컬럼 추가
point_df['pass/fail'] = point_df['평균'].apply(lambda data : "pass" if data >= 80 else "fail")
point_df

국어     영어     수학     과학     코딩     총점    평균 pass/fail
0    70.0  100.0   90.0   70.0   70.0  400.0  80.0      pass
1    90.0  100.0   60.0  100.0   60.0  410.0  82.0      pass
2    70.0   80.0   90.0   90.0   70.0  400.0  80.0      pass
3   100.0   90.0   80.0   70.0   80.0  420.0  84.0      pass
4    60.0   80.0   90.0   90.0   70.0  390.0  78.0      fail
5   100.0   70.0   70.0   80.0  100.0  420.0  84.0      pass
6   100.0  100.0  100.0   70.0   80.0  450.0  90.0      pass
7    80.0  100.0   70.0   60.0   90.0  400.0  80.0      pass
8    70.0   60.0  100.0   60.0   60.0  350.0  70.0      fail
9   100.0   80.0   70.0   90.0  100.0  440.0  88.0      pass
평균   84.0   86.0   82.0   78.0   78.0  408.0  81.6      pass

In [82]:
# groupby, merge(join), pivot