$\alpha = \beta$

$$\alpha = \beta$$

In [2]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sos
import sklearn as sk
import statsmodels.api as sm

In [3]:
from sklearn.datasets import load_iris

In [11]:
iris = load_iris()
iris.data[0,:]

array([5.1, 3.5, 1.4, 0.2])

### 벡터의 차원과 array 의 차원은 다르다.
1. 벡터의 차원 != 배열의 차원
 - 벡터의 차원 : 원소의 갯수
 - 배열의 차원 : 원소의 갯수가 몇개이든, 한 줄로 나타낼 수 있으면 '1차원 배열', 가로와 세로가 있는 여러 줄의 직사각형 형태로 나타낼 수 있으면 '2차원 배열' 이라고 함

2. 예측문제의 입력데이터는 대부분 1줄의 열벡터로 변환
 - 예측문제의 입력데이터는 대부분 벡터로 표시함 
 - 2차원 이미지데이터 -> 1차원 열벡터로 변환해 길게 늘어트린다.(reshape) 

3. 행렬에선 열벡터를 행벡터로 바꿔 표시
     - 데이터를 행렬로 묶어서 표시할 때는 열벡터를 행벡터로 변환해 표시.

# 연습문제 2.1.1

In [5]:
x2 = np.array([[4.9],[3.0],[1.4],[0.2]])
x2

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

# 연습문제 2.1.2

In [7]:
x = np.array([[5.1,3.5,1.4,0.2],[4.9,3.0,1.4,0.2]])
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

# 연습문제 2.1.3

In [22]:
x = np.array([[5.1,3.5,1.4,0.2],[4.9,3.0,1.4,0.2]])
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [23]:
#1. 전치행렬 구하기
x.T

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

In [24]:
#2. 전치의 전치행렬 구하기
x.T.T

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

# 연습문제 2.1.4

In [26]:
#1. 영벡터, 일벡터, 정방행렬, 대각행렬, 항등행렬, 대칭행렬의 예를 하나씩 만들어본다.
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
one_vector = np.ones((3,3))
one_vector

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
square = np.array([[1,2],[3,4]])
square

array([[1, 2],
       [3, 4]])

In [29]:
diag_mat = np.diag((1,2,3))
diag_mat

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
identity_mat = np.eye(3)
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
sym_mat = np.array([[1,2],[2,3]])
sym_mat

array([[1, 2],
       [2, 3]])

# 2.2 벡터와 행렬의 연산


1. 행렬의 +,-
    - 1) 같은 size끼리 +, - 는 Element-wise(요소별) 연산
    - 2) 다른 사이즈, 특히 벡터/행렬 --- 스칼라 간 +,-  => 브로드캐스팅
        - *벡터와 스칼라의 연산 : 관례적으로 스칼라를 벡터로 변환한 연산 허용 ( c -> c*(1벡터) )
    - 3) element-wise로 평균을 빼준 벡터 = 평균제거벡터 (브로드캐스팅 연산)


2. 선형조합


3. 벡터와 벡터의 곱
    - 1) 내적 (inner product, dot product) : element-wise product
    - 2) 내적 결과는 스칼라
    - 3) 내적은 가중합(weighted sum)을 구할 때 사용될 수 있음
        - 가중치의 합치 1일 경우, 내적 = 가중합 = 가중평균
    - 4) 코사인유사도 = 내적 = 두 벡터가 닮은 정도를 정량적으로 나타낸 값
    - 5) 내적은 가중치 벡터와의 곱으로 선형회귀 계산에 활용됨
    
    
4. 특징행렬 (특징벡터를 전치해서 행렬구성) y_hat = Xw, X=특징행렬, w=가중치 벡터
    - 특징벡터 : 각각의 꽃송이, 각각의 아파트 특징값은 열벡터로 구성. But, 특징행렬 구성 시, 특징벡터를 전치하여 행 방향으로 구성


5. 잔차
    - ei = (yi - y_hati)
    - 잔차의 크기 = RSS (잔차제곱합)
    

In [1]:
# [수기과제]
# 선형조합 식 손으로 써보기 (연습과제)
# 가중합 식 손으로 써보기 (연습과제)
# 행렬곱(내적) 실제 손으로 작성 -> A = [[1,2,3],[4,5,6]], B = [[1,2],[3,4],[5,6]], C = AB = ? 
# 연습문제 2.2.4 내적 및 교환법칙 수기실습
# 여러 개의 벡터에 대한 가중합 동시 계산
# 잔차 공식
# 연습문제 2.2.10
# 연습문제 2.2.12
# 연습문제 2.2.13
# 연습문제 2.2.14

In [38]:
x = np.array([[1],[2],[3]])
y = np.array([[4],[5],[6]])

np.dot(x.T,y)

x_ = np.array([1,2,3])
y_ = np.array([4,5,6])
np.dot(x_.T,y_)

32

# 연습문제 2.2.1

In [40]:
# 1. A,B,C 세 회사의 주식은 각각 100, 80, 0만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하고자 한다.

In [41]:
# (1) 주식의 가격과 수량을 각각 p, n벡터로 표시하고 넘파이로 코딩한다.

p = np.array([[100],[80],[50]])
n = np.array([[3],[4],[5]])

In [44]:
# (2) 주식을 매수할 때 필요한 금액을 곱셈으로 표시하고, 넘파이 연산으로 그 값을 계산한다.

amount = p.T@n
amount

array([[870]])

# 연습문제 2.2.2

- 벡터 x의 평균제거벡터 증명 (연습과제)

# 연습문제 2.2.3
- 코사인 유사도

In [46]:
from sklearn.datasets import load_digits
X = load_digits().data

In [62]:
# 1. 내적을 이용하여 첫 번째 이미지와 10번째 이미지의 유사도를 구하라

simil = X[0].T@X[9]
simil

2807.0

In [68]:
# 2. 내적을 이용하여 모든 이미지의 조합에 대해 유사도를 구하라. 어떻게 구현하는 것이 효율적일까?

simil_ttl = X@X.T
simil_ttl

array([[3070., 1866., 2264., ..., 2812., 3006., 2898.],
       [1866., 4209., 3432., ..., 3906., 3083., 3307.],
       [2264., 3432., 4388., ..., 4005., 3063., 3697.],
       ...,
       [2812., 3906., 4005., ..., 5092., 3729., 4598.],
       [3006., 3083., 3063., ..., 3729., 4316., 3850.],
       [2898., 3307., 3697., ..., 4598., 3850., 4938.]])

# 연습문제 2.2.4
- 내적 및 교환법칙 확인(손으로 작성)

# 연습문제 2.2.5

- (1)~(3) : 수기실습작성

In [126]:
# 4. 행렬 Xbar 의 값

from sklearn.datasets import load_iris
X = load_iris().data
X_bar = (1/len(X))*np.ones((len(X),1)).T*np.ones((len(X),1)).T*np.ones((len(X),1))@X
X_bar

array([[5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333,

# 연습문제 2.2.6

- 수기실습

# 연습문제 2.2.7
- 수기실습

# 연습문제 2.2.8
- 수기실습