In [1]:
# 수학 2일차
# 연습문제 2.3.1 수기
# 연습문제 2.3.3-5 수기
# 행렬식 여인수전개 수기
# 연습문제 2.3.7 수기
# 연습문제 2.4.3 수기(1,2번)
# 넘파이를 사용한 역행렬 계산 + 연립방정식 해결 코드
# lstsq방법 활용한 연립방정식 해결 코드
# 보스턴 집값 문제 해결 코드
# 2.4pdf의 8페이지 방정식갯수>미지수갯수 => 해가 없을 수 있음. 열공간으로 정리해보기 수기(재량)
# ---2강
# 연습문제 3.1.2 수기
# 연습문제 3.1.3 수기
# 연습문제 3.1.4 수기
# 연습문제 3.1.5 수기
# 연습문제 3.1.6 수기




In [ ]:
2.3 행렬의 성질

1) 행렬의 부호(정부호)
(positive defi, positive semi defi)
    - 정의
    - 행렬 예시 2개(항등행렬, 대칭행렬)

2) 행렬의 크기
    - norm 정의 (||A||p)
    - 벡터 크기 : L2 norm
    - 행렬 크기 : frobeniums norm
        - 벡터의 (L2 norm)^2 = 내적값 = 벡터의 제곱합 (xT * x)
        
    - code) numpy로 행렬 norm 구해보기
    
3) norm의 4가지 성질
    - 
    - 
    - 
    -
        
4) Trace = 대각합
    - 정의
    - 대각합은 정방행렬에서만 정의됨
    - 항등행렬의 대각합
    - 대각합 성질
        - tr(AB) = tr(BA)
        - tr(ABC) = tr(BCA) = tr(CAB) <= 'trace trick'
        - quadratic form의 trace
    
5) 행렬식
    - 정의
    - 성질
        - 전치행렬의 행렬식
        - 행렬 곱의 행렬식
        - 역행렬의 행렬식
        
    

In [ ]:
2.4 선형 연립방정식과 역행렬

1) 선형연립방정식 = 행렬과 벡터의 곱



2) 역행렬
    - 가역행렬 / 비가역행렬(특이행렬)
    - 대각행렬의 역행렬
    - 역행렬의 성질
        - 전치행렬의 역행렬
    
    - code) 넘파이를 사용한 연립방정식 해결(역행렬 계산)
    - code) lstsq방법 활용한 연립방정식 해결
    
3) 선형 연립방정식과 선형 예측모형
    - 선형 예측모형의 가중치 벡터를 구하기 = 선형 연립방정식 풀기
        (Xw = y, w = (X)-1 y)
        
    - code) 보스턴 집값 예측 문제 코딩
    
4) 미지수의 수와 방정식의 수
    - 방정식의 수 = 미지수의 수
    - 방정식의 수 < 미지수의 수
    - 방정식의 수 > 미지수의 수 -> 최소자승법으로 근사값 구함


In [1]:
2.4 선형 연립방정식과 역행렬

5) 최소제곱법
    - 방정식 갯수 > 미지수 갯수 -> 정학한 해 구할 수 없는 경우, 최소제곱법으로 가장 근접한 답을 찾는다.
    - Ax = b의 해(x)가 없으니, Ax와 b가 가장 근접하게 하는 해(x)를 찾는다. -> e = Ax - b 일 때, 잔차 e를 최소화 하는 해(x)를 찾는 것
    - 잔차를 최소화 = 벡터의 최소화 = norm의 최소화 => (norm)**2 최소화와 같다 = 내적의 최소화
    - eT*e = ||e||^2 = (norm)**2 = (Ax-b)T (Ax-b)
    
    - so, Ax와 b의 잔차의 최소값을 찾는다 -> 잔차의 최소값 = 잔차벡터 norm의 최소값 -> norm**2의 최소값 = 내적의 최소값 -> (Ax-b)T(Ax-b)의 최소값 찾기
    - 이러한 문제를 최소제곱문제 라고 함.

    - 최소제곱법 풀이 과정(Ax = b, x = ?)
    
    
    
    
    
6) 최소제곱법의 계산 => 의사역행렬 (pseudo inverse) 활용
    - 최소제곱법 접근을 통해, Ax^ = b 를 만족하는 근사해(x^)를 찾는 데, 이 때, A의 의사역행렬을 통해 x^를 구할 수 있다.
    - x^ = (A+)b, A+ = 의사역행렬 이라 함
    
    - code) 의사역행렬을 직접 계산해 최소제곱법 근사해 구하기
    - code) np.linalg.lstsq 를 활용해 최소제곱법 근사해 구하기
    
    

SyntaxError: invalid syntax (<ipython-input-1-70bdc540c7f5>, line 1)

In [2]:
3.0 고급 선형대수
3.1 선형대수와 해석기하의 기초

1) 벡터의 길이
    - ||a|| = 
    - 단위벡터

2) 유클리드 거리
    - 정의

3) 벡터의 내적과 삼각함수
    - 내적 = 
    - sin, cos = 
    
4) 직교
    - 정의
    
5) 정규직교
    - 정의
    - 정규직교 벡터의 역행렬 = 전치행렬

6) 코사인 유사도
    - 정의
    - 벡터 간 거리 : 코사인 거리 / 유클리드 거리
    

SyntaxError: invalid syntax (<ipython-input-2-0f735e756a71>, line 1)

# day2 연습문제 (코드)

### 2.4 선형 연립방정식과 역행렬 중 최소자승문제 해결


In [10]:
import numpy as np

A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
b = np.array([[2], [2], [3], [4.1]])

In [6]:
# x를 찾는 방법 => 1. 수도인버스 직접 계산 / 2. 직접 np.linalg.lstsq() 사용

#1. 수도인버스 직접 계산
#A+ = (A.T @ A)-1 @ A.T

Apinv = np.linalg.inv(A.T@A)@A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [9]:
x = Apinv@b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [15]:
#2. np.linalg.lstsq() 적용

x, resid, rank, s = np.linalg.lstsq(A,b)
x, resid, rank, s

/Users/kimjeongseob/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([[1.03333333],
        [0.95      ],
        [1.05      ]]),
 array([0.00166667]),
 3,
 array([3.35753997, 1.15123198, 0.6337115 ]))