In [ ]:
# 연습문제(수학 2일차 마지막)

# 연습문제 3.1.8 (수기)
# 연습문제 3.1.9 (수기
# 연습문제 3.2.2 (수기)
# 연습문제 3.2.3 (수기)


# 연습문제(수학 3일차)

# 연습문제 3.2.5 (수기로 랭크1행렬, 랭크2행렬 만든 후 넘파이 연산결과와 비교)
# 연습문제 3.2.9 (수기 및 코드)
# 연습문제 3.3.1 (수기)
# 연습문제 3.3.2 (수기)
# 연습문제 3.3.3 (수기)
# 연습문제 3.3.4 (수기) -> 모르겠음
# 연습문제 3.3.5 (코드)
# 연습문제 3.3.6 (수기)
# 연습문제 3.3.10 (수기)
# 연습문제 3.4.1 (코드)



In [1]:
03.01 선형대수와 해석기하의 기초

7) 벡터의 분해와 성분
    - a + b = c, c = a와 b로 분해될 수 있음. c라는 벡터의 분해는 (a,b)외에도 수 많은 조합으로 가능

8) 정사영
    - 정사영은 벡터와 직선(or벡터) 간 수직거리 이해에 필요
    
    - 벡터 a를 정사영과 직교성분으로 분해
    - 정사영 길이 = ||a|| cos
    - 정사영 길이 = 내적값 / ||b||
    - 정사영 길이 = 벡터 a와 단위벡터(b의) 내적
    - 정사영 벡터 = 정사영 길이 * 단위벡터
    
    - 벡터 a = a의 정사영 벡터 + a의 직교벡터
    
9) 직선의 방정식
    - 벡터 w에 수직인 직선의 방정식을 구하라
    - 그 직선과 원점사이의 거리를 구하라
    
    
10) 직선과 점사이 거리
    - 벡터 w에 수직인 직선과 x'의 거리를 구하라ㅆㅅㅁ


SyntaxError: invalid syntax (<ipython-input-1-c5535cf9baf3>, line 1)

In [2]:
03. 02 좌표와 변환

1) 선형독립과 선형종속
    - 선형독립 : N(A)의 only solution이 영벡터
    - 선형독립의 벡터들은 서로 직교한다. (데카르트 좌표계의 x축과 y축이 수직인 이유가 여기에 있음. 서로 직교여야 독립)
    - 연습문제 3.2.3
    
2) 선형독립과 연립방정식
    - 선형독립의 논리적 식 (3.2.13식)
    - 선형종속의 대표적인 경우 (03.02 3page)
        1) 벡터의 갯수가 벡터의 차원보다 크면 선형종속
        2) 값이 같은 벡터가 있으면 선형종속
        3) 어떤 벡터가 다른 벡터의 조합이면 선형종속
        
3) 랭크
    - 랭크의 정의
    - 열랭크와 행랭크는 항상 같다
    - rank A <= min(M,N) *A가 M,N행렬일 때 (03.02 4page)
    - code) rank구하는 코드
    
4) 풀랭크
    - 정의
    - Low-랭크 행렬
        - 1랭크 행렬 : N차원 벡터x 1개를 이용해 만든 행렬 (nxn행렬은 사실 벡터1개의 복제품)
        - 2랭크 행렬 : N차원 벡터x 2개를 이용해 만든 행렬
        - 3랭크 행렬 : N차원 벡터x 3개를 이용해 만든 행렬
    
    - 랭크와 역행렬
        - 정방행렬이 풀랭크면, 역행렬이 존재 
            (전단사함수 <-> 역행렬 존재) (rankA=N, rankA=M, M=N => 정방행렬, 풀랭크 조건 = 역행렬 조건)
            (즉, 모두 선형독립인 열벡터만으로 이뤄진 정방행렬 <-> 역행렬 존재)
            (즉, 풀랭크 정방행렬 <-> 역행렬 존재)
            
            
5) 벡터공간과 기저벡터
    - 벡터공간 : 선형독립인 벡터 N개의 선형결합으로 만들어지는 집합
    - 기저벡터 : 벡터공간을 이루는 선형독립인 벡터들
        - 벡터공간의 차원 : 기저벡터의 갯수 (기저벡터 2개로는 2차원 column space 만들 수 있음)
            ex) 만약, 선형독립인 3차원 벡터 2개가 주어졌다면, 2차원 column space는 만들 수 있지만, 3차원 column space는 만들 수 없다.
            (03.02 8page)
            
            
            
    - 정리 : M차원 벡터 N개가 *선형독립* 일 때 (M x N 행렬)
        - N = M  =>  모든 N차원 C(A) 생성 가능 (span of 벡터N개)
        - N > M  =>  갯수가 더 많음. N개 중 일부는 선형종속. 따라서, 선형종속이다. column space 생성 불가
        - N < M  =>  갯수가 더 적음. N차원 C(A)가능. (but, M차원 C(A)는 불가)
            ex) 3차원 벡터 2개가 선형독립.  =>  2차원 C(A) 가능. (but, 3차원 C(A)는 불가.)
        
        
6) 정사영 (shadow to 벡터공간)
    - 정규직교인 기저벡터의 M차원 공간 정사영 (03.02 10page그림, 03.02 11page)
        - 정사영 = 
        - 정사영 길이 = 
    
7) 표준기저벡터
    - e1, e2, ...
    - 좌표 : 기저벡터를 선형조합하여 그 벡터를 나타내기 위한 계수벡터를 의미 (03.02 12page)
        
        
        
        
        

8) 변환행렬
    - 역할 : 기저벡터의 변환, 회전 및 스케일  (03.02 17page, 03.02 19page)
        
        
        
        
    

9) 이미지변환
    - 03.02 23page
    - 연습문제 3.2.9 (수기 및 코드 확인)

SyntaxError: invalid token (<ipython-input-2-d0574353f756>, line 1)

In [ ]:
03.03 고유값 분해

1) 고유값과 고유벡터
    - 정의

    
    - 고유값 분해는 정방행렬에서만 가능
    - 행렬을 곱해서 변환 시, 방향은 변하지 않고 스케일링 효과만 있을 때, 그때의 스케일러를 고유값, 방향을 고유벡터라고 한다.
    - 대표적으로 고유벡터를 단위벡터로 상정해서 얘기한다.
    
    
2) 고유값 계산
    - 특성방정식의 해 찾기 (03.03 2page)

    
    [고유값 갯수]
    - N차 정방행렬의 고유값은 항상 N개 (중근 및 복소수 모두 별개라고 가정 시)
    
    [고유값과 trace, determinent]
    - tr(A) = 고유값 합
    - det(A) = 고유값 곱  *고유값 중 하나라도 존재하면, 역행렬이 존재하지 않는다. (det(A) = 0 이 될테니까)
    
    
3) 고유벡터 계산
    - 특성방정식에 고유값 넣어서 계산
    
    
4) 대각화
    - 고유값 행렬 = diag(람다i)
    - 정방행렬 A 의 고유값분해 = 대각화 (03.03 8page) 
     
5) 대각화 가능 조건
    - full rank는 역행렬. 역행렬은 full rank
    - 고유벡터행렬이 full rank. 선형독립 set이어야 한다.
    
6) 대칭행렬의 고유분해
    - 대칭행렬 => orthogonal 고유벡터행렬 + 실수 고유값 갖는다. (고유값은 실수 + 고유벡터는 서로 직교)
    - 대칭행렬은 항상 대각화가 가능함 (고유벡터 행렬이 full rank -> 고유벡터 행렬의 inverse 가능)
    
    - 만약, 고유벡터들이 정규화된 상태라면
    - 대칭행렬 => orthonormal 고유벡터행렬 + 실수 고유값 갖는다. (고유값은 실수 + 고유벡터는 서로 정규직교)
    - 고유벡터행렬 V는 정규직교행렬... 따라서,  VV.T = I  <==>  V.inv = V.T
    
    - 대칭행렬의 고유분해 (03.03 11page) (고유벡터들이 정규화된 정규직교벡터set 행렬 V)


7) 대칭행렬을 랭크-1 행렬의 합으로 분해 (03.03 12page) (매우 중요)
    - 부분행렬 3번 case로 해석 (수기로 해보기) + 예제 풀이

    
    
    
    
8) 대칭행렬의 고유값 부호
    - 대칭행렬이 양의정부호 <==> 고유값이 모두 양수 (매우 중요)
    - 대칭행렬이 양의준정부호 <==> 고유값이 모두 양수 or 0
    - 둘 다 증명 해보기(꼭 암기는 아니더라도, 해보기!)
    
    
9) 분산행렬
    - 분산행렬 : X.T X 인 정방행렬
    - 분산행렬은 대칭행렬이다.
    - 분산행렬은 양의정부호 + 고유값 >= 0 (분산행렬은 대칭행렬. 대칭행렬이 양의정부호이면, 고유값은 모두 양수)
    - 분산행렬이 양의정부호 증명(꼭 해보기)
    
10) 분산행렬의 역행렬
    - (03.03 17page) *X만 full rank라면, 역행렬 존재하지 않아도.. 그것의 분산행렬인 X.TX의 역행렬이 존재한다는 것.
    
    
    
    
    
    - X가 full rank가 아니라면, 분산행렬의 역행렬이 존재하지 않고 ==> 최소제곱법(Ax = b의 근사해 찾기 위한 수도인버스) 불가
    - (03.03 17page 하단부)
    
    
    
    
    
    
11) 고유분해의 성질 (03.03 18page)
    
    






In [ ]:
03.04 특이값 분해

1) 특이값과 특이벡터 (03.04 1page)





2) 특이값 분해 행렬의 크기 (03.04 3page)
    - 특이값 분해는 모든 행렬에 대해 가능하다. (고유값 분해는 정방행렬A에 대해 + 고유벡터set이 가역적일 때만 대각화 가능)
    - 


3) 특이값 분해의 축소형
    - (03.04 3page)
    - (03.04 4page 상단)
    
    
    
    

    
4) 파이썬을 활용한 특이분해(꼭 해보기) (연습문제 3.4.1)

5) 특이값과 특이벡터의 관계 (03.04 7page)





6) 특이분해와 고유분해의 관계
    - 고유분해를 고려하기 위해, 정방행렬을 만들어주자. 분산행렬을 활용!
    - 행렬 A의 분산행렬을 만들어 생각하면 간단
     
7) 1차원 근사
    - (03.04 10page, 11page)







### 연습문제 3일차

In [2]:
import numpy as np

In [3]:
# 연습문제 3.2.5

x1 = [[1,1],[1,1]]
x2 = [[2,0],[0,2]]

x1_rank = np.linalg.matrix_rank(x1)
x2_rank = np.linalg.matrix_rank(x2)

print(x1_rank,x2_rank)

1 2


In [14]:
# 연습문제 3.3.5 (numpy를 활용한 고유분해)

e = np.array([[2,3],[2,1]])
e_w, e_v = np.linalg.eig(e)
print(e_w, e_v,sep='\n')

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [15]:
x = np.linalg.inv(e_v)
x

array([[ 0.72111026,  0.72111026],
       [-0.56568542,  0.84852814]])

In [62]:
# 연습문제 3.4.1 (numpy를 활용한 특이값분해)

from numpy.linalg import svd
b = np.array([[3,2,2],[2,3,-2]])
U, S, V_T = svd(b,full_matrices=False)
U

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [63]:
np.diag(S)

array([[5., 0.],
       [0., 3.]])

In [64]:
V_T

array([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01]])

In [65]:
U@np.diag(S)@V_T

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])