In [8]:
import tensorflow as tf
import numpy as np

### 1. Tensor의 rank

- scalar
- 1-d tensor
- 2-d tensor
- 3-d tensor

In [2]:
a = tf.constant(2)
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [3]:
print(tf.rank(a))

tf.Tensor(0, shape=(), dtype=int32)


In [4]:
b = tf.constant([1,2])
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
print(tf.rank(b))

tf.Tensor(1, shape=(), dtype=int32)


In [6]:
c = tf.constant([[1,2],[3,4]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
print(tf.rank(c))

tf.Tensor(2, shape=(), dtype=int32)


### 2. Eager mode

- 즉시 실행 모드

In [9]:
a = tf.constant(3)
b = tf.constant(2)

In [11]:
# 기본 연산
# tensor로 출력
print(tf.add(a,b))
print(tf.subtract(a,b))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [13]:
# numpy로 출력
# 보통은, numpy 변환 후(.numpy()) 함수 연산 -> 다시 텐서로 변환(tf.convert_to_tensor())

print(tf.multiply(a,b).numpy())
print(tf.divide(a,b).numpy())

6
1.5


In [14]:
c = tf.add(a,b).numpy()
c_square = np.square(c, dtype=np.float32)
c_tensor = tf.convert_to_tensor(c_square)

In [15]:
print("numpy_array : %0.1f, applying square with numpy : %0.1f,\
      convert_to_tensor : %0.1f" % (c, c_square, c_tensor))

numpy_array : 5.0, applying square with numpy : 25.0,      convert_to_tensor : 25.0


In [16]:
tf.rank(c_square)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

### 3. @tf.function

- **graph형태로 다루고 싶을 때 사용**
- Auto graph : 자동으로 그래프를 생성해주는 기능(데코레이터)
- 이를 통해, 파이썬 코드를 그래프로 변환해 사용 가능 -> 그래프로 변환해 사용한다는 것은 gpu연산이 가능하다는 의미(효율적)
- 하지만, CNN 등의 고비용 연산에서는 성능에 큰 차이를 갖지 못한다는 단점

    - if : tf.cond
    - for/while : tf.while_loop
    - for _ in dataset : dataset.reduce

In [18]:
@tf.function
def square_pos(x):
    if x>0:
        x = x*x
    else:
        x = x*(-1)
    return x

square_pos

In [19]:
def square_pos(x):
    if x>0:
        x = x*x
    else:
        x = x*(-1)
    return x

square_pos

<function __main__.square_pos(x)>

### 4. OR 게이트 구현

In [20]:
tf.random.set_seed(777)

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse

In [22]:
# 데이터셋 준비
x = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([[0],[1],[1],[1]])

In [30]:
# 모델 구성
model = Sequential()

# Dense(hidden_unit 갯수, input_shape) : 1개의 hidden_unit, 2개의 특성을 갖는 1차원 데이터(1-d tensor)를 입력으로 받고, 1개의 출력을 갖는 dense 층
# hidden_unit 갯수 : output size에 영향
# ex) input : [1,0], output : 1
model.add(Dense(1,input_shape=(2,),activation='linear'))

In [27]:
# 모델 준비하기
model.compile(optimizer=SGD(),
              loss = mse,
              metrics = ['acc']) # acc metric은 list 형태로 평가지표를 전달함

In [28]:
# 학습 시키기
model.fit(x,y,epochs=500)

Train on 4 samples
Epoch 1/500
4/4 [==============================] - 0s 40ms/sample - loss: 0.4808 - acc: 0.5000
Epoch 2/500
4/4 [==============================] - 0s 367us/sample - loss: 0.4599 - acc: 0.5000
Epoch 3/500
4/4 [==============================] - 0s 686us/sample - loss: 0.4403 - acc: 0.5000
Epoch 4/500
4/4 [==============================] - 0s 813us/sample - loss: 0.4218 - acc: 0.7500
Epoch 5/500
4/4 [==============================] - 0s 711us/sample - loss: 0.4045 - acc: 0.7500
Epoch 6/500
4/4 [==============================] - 0s 711us/sample - loss: 0.3882 - acc: 0.7500
Epoch 7/500
4/4 [==============================] - 0s 770us/sample - loss: 0.3728 - acc: 0.7500
Epoch 8/500
4/4 [==============================] - 0s 933us/sample - loss: 0.3584 - acc: 0.7500
Epoch 9/500
4/4 [==============================] - 0s 987us/sample - loss: 0.3448 - acc: 0.7500
Epoch 10/500
4/4 [==============================] - 0s 853us/sample - loss: 0.3320 - acc: 0.7500
Epoch 11/500
4/4 [===

Epoch 86/500
4/4 [==============================] - 0s 589us/sample - loss: 0.1073 - acc: 0.7500
Epoch 87/500
4/4 [==============================] - 0s 697us/sample - loss: 0.1068 - acc: 0.7500
Epoch 88/500
4/4 [==============================] - 0s 398us/sample - loss: 0.1063 - acc: 0.7500
Epoch 89/500
4/4 [==============================] - 0s 405us/sample - loss: 0.1059 - acc: 0.7500
Epoch 90/500
4/4 [==============================] - 0s 942us/sample - loss: 0.1054 - acc: 0.7500
Epoch 91/500
4/4 [==============================] - 0s 468us/sample - loss: 0.1049 - acc: 0.7500
Epoch 92/500
4/4 [==============================] - 0s 399us/sample - loss: 0.1044 - acc: 0.7500
Epoch 93/500
4/4 [==============================] - 0s 853us/sample - loss: 0.1040 - acc: 0.7500
Epoch 94/500
4/4 [==============================] - 0s 731us/sample - loss: 0.1035 - acc: 0.7500
Epoch 95/500
4/4 [==============================] - 0s 551us/sample - loss: 0.1031 - acc: 0.7500
Epoch 96/500
4/4 [============

Epoch 170/500
4/4 [==============================] - 0s 441us/sample - loss: 0.0816 - acc: 1.0000
Epoch 171/500
4/4 [==============================] - 0s 542us/sample - loss: 0.0814 - acc: 1.0000
Epoch 172/500
4/4 [==============================] - 0s 559us/sample - loss: 0.0812 - acc: 1.0000
Epoch 173/500
4/4 [==============================] - 0s 825us/sample - loss: 0.0810 - acc: 1.0000
Epoch 174/500
4/4 [==============================] - 0s 456us/sample - loss: 0.0808 - acc: 1.0000
Epoch 175/500
4/4 [==============================] - 0s 854us/sample - loss: 0.0807 - acc: 1.0000
Epoch 176/500
4/4 [==============================] - 0s 475us/sample - loss: 0.0805 - acc: 1.0000
Epoch 177/500
4/4 [==============================] - 0s 831us/sample - loss: 0.0803 - acc: 1.0000
Epoch 178/500
4/4 [==============================] - 0s 576us/sample - loss: 0.0801 - acc: 1.0000
Epoch 179/500
4/4 [==============================] - 0s 628us/sample - loss: 0.0800 - acc: 1.0000
Epoch 180/500
4/4 [=

Epoch 254/500
4/4 [==============================] - 0s 658us/sample - loss: 0.0709 - acc: 1.0000
Epoch 255/500
4/4 [==============================] - 0s 519us/sample - loss: 0.0708 - acc: 1.0000
Epoch 256/500
4/4 [==============================] - 0s 1ms/sample - loss: 0.0707 - acc: 1.0000
Epoch 257/500
4/4 [==============================] - 0s 512us/sample - loss: 0.0706 - acc: 1.0000
Epoch 258/500
4/4 [==============================] - 0s 946us/sample - loss: 0.0706 - acc: 1.0000
Epoch 259/500
4/4 [==============================] - 0s 553us/sample - loss: 0.0705 - acc: 1.0000
Epoch 260/500
4/4 [==============================] - 0s 440us/sample - loss: 0.0704 - acc: 1.0000
Epoch 261/500
4/4 [==============================] - 0s 635us/sample - loss: 0.0703 - acc: 1.0000
Epoch 262/500
4/4 [==============================] - 0s 676us/sample - loss: 0.0703 - acc: 1.0000
Epoch 263/500
4/4 [==============================] - 0s 538us/sample - loss: 0.0702 - acc: 1.0000
Epoch 264/500
4/4 [===

Epoch 338/500
4/4 [==============================] - 0s 401us/sample - loss: 0.0662 - acc: 1.0000
Epoch 339/500
4/4 [==============================] - 0s 670us/sample - loss: 0.0662 - acc: 1.0000
Epoch 340/500
4/4 [==============================] - 0s 455us/sample - loss: 0.0661 - acc: 1.0000
Epoch 341/500
4/4 [==============================] - 0s 820us/sample - loss: 0.0661 - acc: 1.0000
Epoch 342/500
4/4 [==============================] - 0s 396us/sample - loss: 0.0661 - acc: 1.0000
Epoch 343/500
4/4 [==============================] - 0s 352us/sample - loss: 0.0660 - acc: 1.0000
Epoch 344/500
4/4 [==============================] - 0s 894us/sample - loss: 0.0660 - acc: 1.0000
Epoch 345/500
4/4 [==============================] - 0s 829us/sample - loss: 0.0660 - acc: 1.0000
Epoch 346/500
4/4 [==============================] - 0s 471us/sample - loss: 0.0659 - acc: 1.0000
Epoch 347/500
4/4 [==============================] - 0s 514us/sample - loss: 0.0659 - acc: 1.0000
Epoch 348/500
4/4 [=

Epoch 423/500
4/4 [==============================] - 0s 705us/sample - loss: 0.0641 - acc: 1.0000
Epoch 424/500
4/4 [==============================] - 0s 503us/sample - loss: 0.0641 - acc: 1.0000
Epoch 425/500
4/4 [==============================] - 0s 564us/sample - loss: 0.0641 - acc: 1.0000
Epoch 426/500
4/4 [==============================] - 0s 861us/sample - loss: 0.0641 - acc: 1.0000
Epoch 427/500
4/4 [==============================] - 0s 766us/sample - loss: 0.0641 - acc: 1.0000
Epoch 428/500
4/4 [==============================] - 0s 710us/sample - loss: 0.0641 - acc: 1.0000
Epoch 429/500
4/4 [==============================] - 0s 580us/sample - loss: 0.0641 - acc: 1.0000
Epoch 430/500
4/4 [==============================] - 0s 975us/sample - loss: 0.0640 - acc: 1.0000
Epoch 431/500
4/4 [==============================] - 0s 566us/sample - loss: 0.0640 - acc: 1.0000
Epoch 432/500
4/4 [==============================] - 0s 577us/sample - loss: 0.0640 - acc: 1.0000
Epoch 433/500
4/4 [=

In [29]:
# 가중치 확인
model.get_weights()

[array([[0.4478314],
        [0.5199499]], dtype=float32),
 array([0.26910788], dtype=float32)]

### 5. 벡터의 내적

In [31]:
x = tf.random.uniform((10,5)) # uniform 분포에서 해당 크기만큼 난수를 생성
w = tf.random.uniform((5,3))
d = tf.matmul(x,w)

print(f"x와 w의 내적 결과 크기 : {d.shape}")

x와 w의 내적 결과 크기 : (10, 3)


### 6. XOR + MLP

In [32]:
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.losses import mse

tf.random.set_seed(777)

# 데이터 준비
data = np.array([[0,0],[1,0],[0,1],[1,1]])
label = np.array([[0],[1],[1],[0]])

# 모델 구성
model = Sequential()
model.add(Dense(32, input_shape=(2,), activation = 'relu'))
model.add(Dense(1, activation='sigmoid'))

# 모델 준비하기
model.compile(optimizer=RMSprop(),
              loss = mse,
              metrics = ['acc'])

# 모델 학습
model.fit(data,label, epochs=1000)

Train on 4 samples
Epoch 1/1000
4/4 [==============================] - 0s 65ms/sample - loss: 0.2646 - acc: 0.5000
Epoch 2/1000
4/4 [==============================] - 0s 539us/sample - loss: 0.2621 - acc: 0.2500
Epoch 3/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2603 - acc: 0.2500
Epoch 4/1000
4/4 [==============================] - 0s 812us/sample - loss: 0.2589 - acc: 0.2500
Epoch 5/1000
4/4 [==============================] - 0s 632us/sample - loss: 0.2578 - acc: 0.2500
Epoch 6/1000
4/4 [==============================] - 0s 612us/sample - loss: 0.2568 - acc: 0.2500
Epoch 7/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2558 - acc: 0.2500
Epoch 8/1000
4/4 [==============================] - 0s 958us/sample - loss: 0.2550 - acc: 0.2500
Epoch 9/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.2541 - acc: 0.2500
Epoch 10/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2533 - acc: 0.2500
Epoch 11/1000
4/4 [

Epoch 85/1000
4/4 [==============================] - 0s 642us/sample - loss: 0.2171 - acc: 1.0000
Epoch 86/1000
4/4 [==============================] - 0s 665us/sample - loss: 0.2167 - acc: 1.0000
Epoch 87/1000
4/4 [==============================] - 0s 640us/sample - loss: 0.2163 - acc: 1.0000
Epoch 88/1000
4/4 [==============================] - 0s 688us/sample - loss: 0.2159 - acc: 1.0000
Epoch 89/1000
4/4 [==============================] - 0s 962us/sample - loss: 0.2155 - acc: 1.0000
Epoch 90/1000
4/4 [==============================] - 0s 932us/sample - loss: 0.2151 - acc: 1.0000
Epoch 91/1000
4/4 [==============================] - 0s 967us/sample - loss: 0.2147 - acc: 1.0000
Epoch 92/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2143 - acc: 1.0000
Epoch 93/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2138 - acc: 1.0000
Epoch 94/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2135 - acc: 1.0000
Epoch 95/1000
4/4 [=======

4/4 [==============================] - 0s 566us/sample - loss: 0.1832 - acc: 1.0000
Epoch 169/1000
4/4 [==============================] - 0s 667us/sample - loss: 0.1828 - acc: 1.0000
Epoch 170/1000
4/4 [==============================] - 0s 613us/sample - loss: 0.1824 - acc: 1.0000
Epoch 171/1000
4/4 [==============================] - 0s 385us/sample - loss: 0.1819 - acc: 1.0000
Epoch 172/1000
4/4 [==============================] - 0s 411us/sample - loss: 0.1815 - acc: 1.0000
Epoch 173/1000
4/4 [==============================] - 0s 483us/sample - loss: 0.1810 - acc: 1.0000
Epoch 174/1000
4/4 [==============================] - 0s 506us/sample - loss: 0.1806 - acc: 1.0000
Epoch 175/1000
4/4 [==============================] - 0s 611us/sample - loss: 0.1801 - acc: 1.0000
Epoch 176/1000
4/4 [==============================] - 0s 630us/sample - loss: 0.1797 - acc: 1.0000
Epoch 177/1000
4/4 [==============================] - 0s 446us/sample - loss: 0.1793 - acc: 1.0000
Epoch 178/1000
4/4 [=====

Epoch 251/1000
4/4 [==============================] - 0s 523us/sample - loss: 0.1468 - acc: 1.0000
Epoch 252/1000
4/4 [==============================] - 0s 833us/sample - loss: 0.1464 - acc: 1.0000
Epoch 253/1000
4/4 [==============================] - 0s 504us/sample - loss: 0.1460 - acc: 1.0000
Epoch 254/1000
4/4 [==============================] - 0s 532us/sample - loss: 0.1455 - acc: 1.0000
Epoch 255/1000
4/4 [==============================] - 0s 586us/sample - loss: 0.1451 - acc: 1.0000
Epoch 256/1000
4/4 [==============================] - 0s 546us/sample - loss: 0.1447 - acc: 1.0000
Epoch 257/1000
4/4 [==============================] - 0s 526us/sample - loss: 0.1442 - acc: 1.0000
Epoch 258/1000
4/4 [==============================] - 0s 666us/sample - loss: 0.1438 - acc: 1.0000
Epoch 259/1000
4/4 [==============================] - 0s 486us/sample - loss: 0.1433 - acc: 1.0000
Epoch 260/1000
4/4 [==============================] - 0s 660us/sample - loss: 0.1430 - acc: 1.0000
Epoch 261/

Epoch 334/1000
4/4 [==============================] - 0s 554us/sample - loss: 0.1118 - acc: 1.0000
Epoch 335/1000
4/4 [==============================] - 0s 445us/sample - loss: 0.1114 - acc: 1.0000
Epoch 336/1000
4/4 [==============================] - 0s 492us/sample - loss: 0.1110 - acc: 1.0000
Epoch 337/1000
4/4 [==============================] - 0s 580us/sample - loss: 0.1105 - acc: 1.0000
Epoch 338/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1101 - acc: 1.0000
Epoch 339/1000
4/4 [==============================] - 0s 366us/sample - loss: 0.1098 - acc: 1.0000
Epoch 340/1000
4/4 [==============================] - 0s 372us/sample - loss: 0.1093 - acc: 1.0000
Epoch 341/1000
4/4 [==============================] - 0s 636us/sample - loss: 0.1090 - acc: 1.0000
Epoch 342/1000
4/4 [==============================] - 0s 376us/sample - loss: 0.1085 - acc: 1.0000
Epoch 343/1000
4/4 [==============================] - 0s 439us/sample - loss: 0.1081 - acc: 1.0000
Epoch 344/10

Epoch 417/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0798 - acc: 1.0000
Epoch 418/1000
4/4 [==============================] - 0s 822us/sample - loss: 0.0793 - acc: 1.0000
Epoch 419/1000
4/4 [==============================] - 0s 409us/sample - loss: 0.0791 - acc: 1.0000
Epoch 420/1000
4/4 [==============================] - 0s 576us/sample - loss: 0.0786 - acc: 1.0000
Epoch 421/1000
4/4 [==============================] - 0s 435us/sample - loss: 0.0783 - acc: 1.0000
Epoch 422/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0779 - acc: 1.0000
Epoch 423/1000
4/4 [==============================] - 0s 372us/sample - loss: 0.0776 - acc: 1.0000
Epoch 424/1000
4/4 [==============================] - 0s 630us/sample - loss: 0.0772 - acc: 1.0000
Epoch 425/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0769 - acc: 1.0000
Epoch 426/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0765 - acc: 1.0000
Epoch 427/1000
4/4

Epoch 501/1000
4/4 [==============================] - 0s 433us/sample - loss: 0.0526 - acc: 1.0000
Epoch 502/1000
4/4 [==============================] - 0s 434us/sample - loss: 0.0524 - acc: 1.0000
Epoch 503/1000
4/4 [==============================] - 0s 538us/sample - loss: 0.0520 - acc: 1.0000
Epoch 504/1000
4/4 [==============================] - 0s 849us/sample - loss: 0.0518 - acc: 1.0000
Epoch 505/1000
4/4 [==============================] - 0s 481us/sample - loss: 0.0515 - acc: 1.0000
Epoch 506/1000
4/4 [==============================] - 0s 556us/sample - loss: 0.0512 - acc: 1.0000
Epoch 507/1000
4/4 [==============================] - 0s 674us/sample - loss: 0.0509 - acc: 1.0000
Epoch 508/1000
4/4 [==============================] - 0s 530us/sample - loss: 0.0507 - acc: 1.0000
Epoch 509/1000
4/4 [==============================] - 0s 418us/sample - loss: 0.0504 - acc: 1.0000
Epoch 510/1000
4/4 [==============================] - 0s 616us/sample - loss: 0.0501 - acc: 1.0000
Epoch 511/

Epoch 584/1000
4/4 [==============================] - 0s 867us/sample - loss: 0.0325 - acc: 1.0000
Epoch 585/1000
4/4 [==============================] - 0s 778us/sample - loss: 0.0322 - acc: 1.0000
Epoch 586/1000
4/4 [==============================] - 0s 411us/sample - loss: 0.0321 - acc: 1.0000
Epoch 587/1000
4/4 [==============================] - 0s 516us/sample - loss: 0.0318 - acc: 1.0000
Epoch 588/1000
4/4 [==============================] - 0s 990us/sample - loss: 0.0317 - acc: 1.0000
Epoch 589/1000
4/4 [==============================] - 0s 415us/sample - loss: 0.0314 - acc: 1.0000
Epoch 590/1000
4/4 [==============================] - 0s 485us/sample - loss: 0.0313 - acc: 1.0000
Epoch 591/1000
4/4 [==============================] - 0s 562us/sample - loss: 0.0310 - acc: 1.0000
Epoch 592/1000
4/4 [==============================] - 0s 766us/sample - loss: 0.0309 - acc: 1.0000
Epoch 593/1000
4/4 [==============================] - 0s 683us/sample - loss: 0.0307 - acc: 1.0000
Epoch 594/

Epoch 667/1000
4/4 [==============================] - 0s 742us/sample - loss: 0.0188 - acc: 1.0000
Epoch 668/1000
4/4 [==============================] - 0s 653us/sample - loss: 0.0186 - acc: 1.0000
Epoch 669/1000
4/4 [==============================] - 0s 494us/sample - loss: 0.0185 - acc: 1.0000
Epoch 670/1000
4/4 [==============================] - 0s 943us/sample - loss: 0.0184 - acc: 1.0000
Epoch 671/1000
4/4 [==============================] - 0s 453us/sample - loss: 0.0182 - acc: 1.0000
Epoch 672/1000
4/4 [==============================] - 0s 736us/sample - loss: 0.0181 - acc: 1.0000
Epoch 673/1000
4/4 [==============================] - 0s 552us/sample - loss: 0.0180 - acc: 1.0000
Epoch 674/1000
4/4 [==============================] - 0s 901us/sample - loss: 0.0179 - acc: 1.0000
Epoch 675/1000
4/4 [==============================] - 0s 817us/sample - loss: 0.0177 - acc: 1.0000
Epoch 676/1000
4/4 [==============================] - 0s 561us/sample - loss: 0.0176 - acc: 1.0000
Epoch 677/

Epoch 751/1000
4/4 [==============================] - 0s 483us/sample - loss: 0.0101 - acc: 1.0000
Epoch 752/1000
4/4 [==============================] - 0s 533us/sample - loss: 0.0101 - acc: 1.0000
Epoch 753/1000
4/4 [==============================] - 0s 616us/sample - loss: 0.0100 - acc: 1.0000
Epoch 754/1000
4/4 [==============================] - 0s 435us/sample - loss: 0.0099 - acc: 1.0000
Epoch 755/1000
4/4 [==============================] - 0s 546us/sample - loss: 0.0098 - acc: 1.0000
Epoch 756/1000
4/4 [==============================] - 0s 584us/sample - loss: 0.0098 - acc: 1.0000
Epoch 757/1000
4/4 [==============================] - 0s 473us/sample - loss: 0.0097 - acc: 1.0000
Epoch 758/1000
4/4 [==============================] - 0s 754us/sample - loss: 0.0096 - acc: 1.0000
Epoch 759/1000
4/4 [==============================] - 0s 484us/sample - loss: 0.0095 - acc: 1.0000
Epoch 760/1000
4/4 [==============================] - 0s 652us/sample - loss: 0.0095 - acc: 1.0000
Epoch 761/

Epoch 834/1000
4/4 [==============================] - 0s 454us/sample - loss: 0.0052 - acc: 1.0000
Epoch 835/1000
4/4 [==============================] - 0s 414us/sample - loss: 0.0051 - acc: 1.0000
Epoch 836/1000
4/4 [==============================] - 0s 422us/sample - loss: 0.0051 - acc: 1.0000
Epoch 837/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0051 - acc: 1.0000
Epoch 838/1000
4/4 [==============================] - 0s 552us/sample - loss: 0.0050 - acc: 1.0000
Epoch 839/1000
4/4 [==============================] - 0s 373us/sample - loss: 0.0050 - acc: 1.0000
Epoch 840/1000
4/4 [==============================] - 0s 759us/sample - loss: 0.0049 - acc: 1.0000
Epoch 841/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0049 - acc: 1.0000
Epoch 842/1000
4/4 [==============================] - 0s 376us/sample - loss: 0.0048 - acc: 1.0000
Epoch 843/1000
4/4 [==============================] - 0s 577us/sample - loss: 0.0048 - acc: 1.0000
Epoch 844/1000

Epoch 917/1000
4/4 [==============================] - 0s 554us/sample - loss: 0.0025 - acc: 1.0000
Epoch 918/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0025 - acc: 1.0000
Epoch 919/1000
4/4 [==============================] - 0s 533us/sample - loss: 0.0025 - acc: 1.0000
Epoch 920/1000
4/4 [==============================] - 0s 550us/sample - loss: 0.0024 - acc: 1.0000
Epoch 921/1000
4/4 [==============================] - 0s 858us/sample - loss: 0.0024 - acc: 1.0000
Epoch 922/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0024 - acc: 1.0000
Epoch 923/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0024 - acc: 1.0000
Epoch 924/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.0024 - acc: 1.0000
Epoch 925/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0023 - acc: 1.0000
Epoch 926/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0023 - acc: 1.0000
Epoch 927/1000
4/4 [==

### 7. Keras의 개발과정

```python
1. 데이터셋 준비

2. model 구성 (sequential, add)
    1) model = Sequential()
    2) model.add(Dense(32, input_shape=(2,), activation='relu')) # 첫 층은 항상 input_shape를 전달해줘야 함
    3) model.add(Dense(1, activation='sigmoid')) # 첫 층 이후부턴, input_shape는 자동으로 이전 층에서 전달받음
    
3. model 학습과정 설정 (compile)
    1) model.compile(optimizer='', loss='', metrics= [])
    
4. 학습 (fit)
    1) model.fit(data, label, epochs=, validation_data=(val_data, val_label))
    
5. 평가, 예측
    1) model.evaluate(data, label)
    2) model.predict(data)
        
```

### 8. practice

- Perceptron_single-layer (XOR problem)

In [33]:
data = np.array([[0,0],[1,0],[0,1],[1,1]])
label = np.array([[0],[1],[1],[0]])

In [41]:
# 모델 구성
model_single = Sequential()
model_single.add(Dense(1, input_shape=(2,), activation='linear'))

model_MLP = Sequential()
model_MLP.add(Dense(32, input_shape=(2,), activation='relu'))
model_MLP.add(Dense(1, activation='sigmoid'))

# 학습 설정
model_single.compile(optimizer='sgd', loss='mse', metrics=['acc'])

model_MLP.compile(optimizer=RMSprop(), loss=mse, metrics=['acc'])

# 학습
model_single.fit(data, label, epochs=100)


Train on 4 samples
Epoch 1/100
4/4 [==============================] - 0s 38ms/sample - loss: 0.9124 - acc: 0.5000
Epoch 2/100
4/4 [==============================] - 0s 791us/sample - loss: 0.9048 - acc: 0.5000
Epoch 3/100
4/4 [==============================] - 0s 825us/sample - loss: 0.8973 - acc: 0.5000
Epoch 4/100
4/4 [==============================] - 0s 700us/sample - loss: 0.8899 - acc: 0.5000
Epoch 5/100
4/4 [==============================] - 0s 935us/sample - loss: 0.8827 - acc: 0.5000
Epoch 6/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.8757 - acc: 0.5000
Epoch 7/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.8687 - acc: 0.5000
Epoch 8/100
4/4 [==============================] - 0s 946us/sample - loss: 0.8619 - acc: 0.5000
Epoch 9/100
4/4 [==============================] - 0s 985us/sample - loss: 0.8552 - acc: 0.5000
Epoch 10/100
4/4 [==============================] - 0s 2ms/sample - loss: 0.8486 - acc: 0.5000
Epoch 11/100
4/4 [=========

Epoch 86/100
4/4 [==============================] - 0s 990us/sample - loss: 0.5323 - acc: 0.5000
Epoch 87/100
4/4 [==============================] - 0s 737us/sample - loss: 0.5296 - acc: 0.5000
Epoch 88/100
4/4 [==============================] - 0s 456us/sample - loss: 0.5270 - acc: 0.5000
Epoch 89/100
4/4 [==============================] - 0s 611us/sample - loss: 0.5243 - acc: 0.5000
Epoch 90/100
4/4 [==============================] - 0s 576us/sample - loss: 0.5217 - acc: 0.5000
Epoch 91/100
4/4 [==============================] - 0s 744us/sample - loss: 0.5191 - acc: 0.5000
Epoch 92/100
4/4 [==============================] - 0s 875us/sample - loss: 0.5166 - acc: 0.5000
Epoch 93/100
4/4 [==============================] - 0s 452us/sample - loss: 0.5140 - acc: 0.5000
Epoch 94/100
4/4 [==============================] - 0s 474us/sample - loss: 0.5115 - acc: 0.5000
Epoch 95/100
4/4 [==============================] - 0s 634us/sample - loss: 0.5091 - acc: 0.5000
Epoch 96/100
4/4 [============

In [42]:
# 평가
model_single.evaluate(data, label)

4/4 [==============================] - 0s 16ms/sample - loss: 0.4947 - acc: 0.5000


[0.4946560561656952, 0.5]

In [43]:
# 예측
model_single.predict(data)

array([[ 0.20007104],
       [ 1.0976498 ],
       [-0.20242068],
       [ 0.6951581 ]], dtype=float32)

In [45]:
# MLP 학습, 예측
model_MLP.fit(data, label, epochs=100)

Train on 4 samples
Epoch 1/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.2555 - acc: 0.5000
Epoch 2/100
4/4 [==============================] - 0s 791us/sample - loss: 0.2548 - acc: 0.5000
Epoch 3/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.2540 - acc: 0.5000
Epoch 4/100
4/4 [==============================] - 0s 5ms/sample - loss: 0.2533 - acc: 0.5000
Epoch 5/100
4/4 [==============================] - 0s 2ms/sample - loss: 0.2525 - acc: 0.5000
Epoch 6/100
4/4 [==============================] - 0s 825us/sample - loss: 0.2518 - acc: 0.5000
Epoch 7/100
4/4 [==============================] - 0s 2ms/sample - loss: 0.2511 - acc: 0.5000
Epoch 8/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.2505 - acc: 0.5000
Epoch 9/100
4/4 [==============================] - 0s 826us/sample - loss: 0.2498 - acc: 0.5000
Epoch 10/100
4/4 [==============================] - 0s 3ms/sample - loss: 0.2492 - acc: 0.5000
Epoch 11/100
4/4 [================

Epoch 86/100
4/4 [==============================] - 0s 410us/sample - loss: 0.2111 - acc: 1.0000
Epoch 87/100
4/4 [==============================] - 0s 647us/sample - loss: 0.2107 - acc: 1.0000
Epoch 88/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.2103 - acc: 1.0000
Epoch 89/100
4/4 [==============================] - 0s 367us/sample - loss: 0.2099 - acc: 1.0000
Epoch 90/100
4/4 [==============================] - 0s 490us/sample - loss: 0.2096 - acc: 1.0000
Epoch 91/100
4/4 [==============================] - 0s 700us/sample - loss: 0.2091 - acc: 1.0000
Epoch 92/100
4/4 [==============================] - 0s 538us/sample - loss: 0.2088 - acc: 1.0000
Epoch 93/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.2084 - acc: 1.0000
Epoch 94/100
4/4 [==============================] - 0s 578us/sample - loss: 0.2080 - acc: 1.0000
Epoch 95/100
4/4 [==============================] - 0s 423us/sample - loss: 0.2076 - acc: 1.0000
Epoch 96/100
4/4 [================

In [53]:
model_MLP.predict(data)

array([[0.48736542],
       [0.5699035 ],
       [0.5387777 ],
       [0.4312369 ]], dtype=float32)