In [1]:
list_ = [1,2,3,4,5]
a = np.array(list_)
a

array([1, 2, 3, 4, 5])

In [2]:
type(a)

numpy.ndarray

In [3]:
list__ = [[1,2],[3,4]]
b = np.array(list__)
b

array([[1, 2],
       [3, 4]])

In [4]:
type(b)

numpy.ndarray

In [5]:
np.zeros(shape=10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones(shape=(3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full(shape=(3,5),fill_value=2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [12]:
np.full(shape=(3,5),fill_value=2,dtype=np.float)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [23]:
np.empty((3,6))

array([[4.0003, 1.658 , 4.8288, 4.3534, 1.6016, 3.7947],
       [4.7343, 1.5768, 3.2396, 5.214 , 1.6077, 3.3449],
       [5.6481, 1.6274, 3.3455, 5.9296, 1.5929, 2.8223]])

In [24]:
test_np = np.array([[1,2],[3,4],[5,6]])
test_np

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
np.ones_like(test_np)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [26]:
np.zeros_like(test_np)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [27]:
np.full_like(test_np,fill_value=3)

array([[3, 3],
       [3, 3],
       [3, 3]])

In [28]:
np.empty_like(test_np)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [29]:
test_np

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
test_np+np.full_like(test_np, fill_value=10)

array([[11, 12],
       [13, 14],
       [15, 16]])