**reshape, resize는 같은 역할**
```

1.numpy.reshape
2.numpy.resize
3.ndarray.reshape
4.ndarray.resize

```

[차이점]
1. resize => in_place 연산이라는 점이 차이
2. reshape => return 값이 본 데이터의 참조값. 따라서, 원본이 바뀌면 reshape한 데이터도 바뀜

    *원본 바뀌어도 reshape 데이터 영향 받길 원치 않으면, np.array.reshape( () ).copy() 로 '.copy()'활용

    ex)
        a = np.full((2,6), fill_value=2)
        b = a.reshape((4,3))
        a[1] = 10
            => b(reshape된)도 바뀜




In [17]:
a = np.full((3,4), fill_value=3)
a

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [18]:
b = a.reshape((2,6))
c = a.reshape((2,6)).copy()
b

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [19]:
a[0] = 10

In [20]:
b

array([[10, 10, 10, 10,  3,  3],
       [ 3,  3,  3,  3,  3,  3]])

In [21]:
c

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])