- Making ndarray
- Information About ndarray : shape, size/itemsize, dtype
- ndarray Indexing and Slicing
- Reshape Resize and Vectorization

# Quiz

```
[ch1]

1. making ndarray 방법 5가지(entry가 무엇이든)
2. ndarray의 information 중, entry 당 소비하는 memory 크기를 반환하는 함수는?
3. ndarray의 information 중, entry 갯수를 반환하는 함수는?
4. a가 3x4의 list type일 때, (1,1) entry를 인덱싱하는 방법은? / a가 ndarray라면?
5. ndarray.resize((3,4)) / ndarray.reshape((3,4)) 의 차이점은?

```

**Chapter1 ndarray_Notebook1 Making ndarray1-2**

```
1. np.array( [ ] )
2. np.zeros( shape )
3. np.ones( shape )
4. np.empty( shape )
5. np.full( shape, fill_value )

```
```
1. np.zeros_like( ndarray )
2. np.ones_like( ndarray )
3. np.empty_like( ndarray )
4. np.full_like( ndarray, fill_value )

```

**Chapter1 ndarray: Notebook3 Information About ndarray**

```
1. shape

    np.array.shape
        => return ( , )
    
2. size

    np.array.size
        => return "entry 갯수"
        
            ex) np.ones((2,3)).size
                => return 6
                
    np.array.itemsize
        => return "entry 당 소비하는 memory 크기"
            
            ex) np.ones((2,3), dtype=np.int)
                => return 64
                np.ones((2,3), dtype=np.int8)
                => return 8
    
    *numpy는 기본적으로 64bit를 할당함. image데이터는 entry당 8bit이므로, default 64비트를 할당할 경우, 
     entry당 (64-8)bit의 memory loss가 발생하는 것. 따라서, 주의해서 dtype을 설정해야 함.

3. dtype

    np.array.dtype
    
    
```

**Chapter1 ndarray: Notebook4-5 ndarray Indexing and Slicing**

```

1. list 타입의 matrix indexing / slicing

    a = list([[1,2],[2,3],[3,4]])
    a[1][1]
        => 3

2. ndarray 타입의 matrix indexing / slicing

    b = np.array(a)
    b[1,1]
        => 3
        
3. list / ndarray의 indexing/slicing 차이

    list => 인덱싱/슬라이싱 시, 복사본을 만들어 return.
    
    ndarray => 인덱싱/슬라이싱 시, 원본을 그대로 참조해 return. (따라서, 원본 값이 바뀌면, 인덱싱/슬라이싱한 주머니 값도 바뀜)
    
        *따라서, ndarray를 인덱싱/슬라이싱 시, np.array[1:,].copy()로 list처럼 복사본을 만들어 저장하도록 하기도 함.
        *ndarray는 워낙 큰 데이터를 다루므로, memory consumption 최소화하기 위한 철학이 깔려있는 것.


```

**Chapter1 ndarray: Notebook6 Reshape Resize and Vectorization**

**reshape, resize는 같은 역할**
```

1.numpy.reshape
2.numpy.resize
3.ndarray.reshape
4.ndarray.resize

```

[차이점]
1. resize => in_place 연산이라는 점이 차이
2. reshape => return 값이 본 데이터의 참조값. 따라서, 원본이 바뀌면 reshape한 데이터도 바뀜

    *원본 바뀌어도 reshape 데이터 영향 받길 원치 않으면, np.array.reshape( () ).copy() 로 '.copy()'활용

    ex)
        a = np.full((2,6), fill_value=2)
        b = a.reshape((4,3))
        a[1] = 10
            => b(reshape된)도 바뀜




In [17]:
a = np.full((3,4), fill_value=3)
a

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [18]:
b = a.reshape((2,6))
c = a.reshape((2,6)).copy()
b

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [19]:
a[0] = 10

In [20]:
b

array([[10, 10, 10, 10,  3,  3],
       [ 3,  3,  3,  3,  3,  3]])

In [21]:
c

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])