In [1]:
e1 = np.array([[1],[0],[0]])
e2 = np.array([[0],[1],[0]])
e3 = np.array([[0],[0],[1]])

In [3]:
inner_e1_e2 = e1.T@np.array([[2,1,0],[1,2,-1],[0,-1,2]])@e2
inner_e2_e3 = e2.T@np.array([[2,1,0],[1,2,-1],[0,-1,2]])@e3

In [4]:
inner_e1_e2 + inner_e2_e3

array([[0]])

In [5]:
inner_e1_e2

array([[1]])

In [6]:
inner_e2_e3

array([[-1]])

In [7]:
x = np.array([[-1/2],[1],[1/2]])

In [9]:
inner_x_x = x.T@np.array([[2,1,0],[1,2,-1],[0,-1,2]])@x

In [10]:
inner_x_x

array([[1.]])