In [13]:
a = np.array([[-1,-(1/2),1],[0,-(1/2),1],[1,1,1]])
b = np.array([[0,0,0],[0,0,0],[0,0,3]])

In [14]:
a@b@np.linalg.inv(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
a_ = np.array([[-1,-1,1],[1,0,1],[0,1,1]])

In [5]:
a_@b@np.linalg.inv(a_)

array([[ 1., -2.,  1.],
       [-1.,  2., -1.],
       [ 0.,  0.,  0.]])

In [6]:
A = np.array([[1,1,1],[1,1,1],[1,1,1]])
w,v = np.linalg.eig(A)

In [7]:
w

array([ 3.00000000e+00,  6.16297582e-33, -7.50963641e-17])

In [8]:
v

array([[ 5.77350269e-01, -6.51147040e-17,  6.09781659e-01],
       [ 5.77350269e-01, -7.07106781e-01, -7.75129861e-01],
       [ 5.77350269e-01,  7.07106781e-01,  1.65348202e-01]])

In [9]:
-(1/2)

-0.5

In [11]:
temp1 = np.array([[-1,-1,1],[1,0,1],[0,1,1]])
temp1_1 = np.array([[-1,-(1/2),1],[1,-(1/2),1],[0,1,1]])
temp2 = np.array([[7,0,0],[0,1,0],[0,0,1]])
temp3 = np.linalg.inv(temp1)
temp3_1 = np.linalg.inv(temp1_1)

temp1_1@temp2@temp3_1

array([[ 4.00000000e+00, -3.00000000e+00,  0.00000000e+00],
       [-3.00000000e+00,  4.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17, -5.55111512e-17,  1.00000000e+00]])

In [12]:
temp1@temp2@temp3

array([[ 3.00000000e+00, -4.00000000e+00,  2.00000000e+00],
       [-2.00000000e+00,  5.00000000e+00, -2.00000000e+00],
       [-5.55111512e-17, -5.55111512e-17,  1.00000000e+00]])