# 4.8 예제
- SVD 전개

In [48]:
A = np.array([[3,2,2],[2,3,-2]])

In [49]:
A.T@A

array([[13, 12,  2],
       [12, 13, -2],
       [ 2, -2,  8]])

In [50]:
u = np.array([[1,3/4,0],[1,-(3/4),0]])
s = np.array([[5,0,0],[0,3,0],[0,0,0]])
v = np.array([[1,1/4,-2],[1,-(1/4),2],[0,1,1]])

In [51]:
u@s@np.linalg.inv(v)

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [53]:
A == u@s@np.linalg.inv(v)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [54]:
u@s@v.T

array([[ 5.5625,  4.4375,  2.25  ],
       [ 4.4375,  5.5625, -2.25  ]])

In [55]:
A == u@s@v.T

array([[False, False, False],
       [False, False, False]])

# 4.8 예제
- SVD 전개
- U, V 를 ONB로 전개

In [95]:
temp1 = np.array([[1/(np.sqrt(2)),2*np.sqrt(2)/12,-(2/3)]])
temp2 = np.array([[1/np.sqrt(2),-(2*np.sqrt(2)/12),2/3]])
temp3 = np.array([[0,2*np.sqrt(2)/3,1/3]])

In [96]:
V = np.vstack([temp1,temp2,temp3])
V

In [99]:
V.T@V

array([[ 1.00000000e+00, -1.24117317e-17, -7.66449057e-18],
       [-1.24117317e-17,  1.00000000e+00, -1.74454718e-17],
       [-7.66449057e-18, -1.74454718e-17,  1.00000000e+00]])