# 19. Module, Package, Try_except, Numpy1_20191011_03_Day4_3부

# Numpy, Pandas

- 행렬 데이터 생성, 수정, 계산 등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 매트릭스

In [1]:
import numpy as np

In [15]:
# 행렬 데이터 생성

array = np.array([1,2,3])
type(array)

# np.array( ) 라는 함수를 사용하면, 'numpy.ndarray' 라는 데이터타입이 만들어지는 것

# [과정]
# np 모듈 안의 array( [ ] ) 함수를 호출 -> [1,2,3] 데이터를 array함수에 넣는다 ->
# -> array가 저장된 클래스의 object가 생성되어 array에 저장되는 것 

# [결론]
# array함수와 array object는 같은 클래스에 소속 (np모듈의 array함수 호출 -> 같은 클래스 내 object생성('array'))
# ojbect 안에는 [1,2,3] 이 들어있을 것
# 함수 array소속 클래스에는 "def __repr__(self): " 이 선언되어 있을 것 (array만 쳐도 return이 나오니까!)
# Numpy 연산은 numpy.ndarray 타입끼리만 가능
# ndarray 타입은 int 타입 value만 가능!

numpy.ndarray

## 2차원 생성

In [14]:
# 2차원 행렬 생성

array2 = np.array(
    [[1,2,3],
     [4,5,6]]
)

print(array2,array2.ndim,array2.shape,sep='\n')

[[1 2 3]
 [4 5 6]]
2
(2, 3)


## 행렬 모양 변경하기

In [17]:
# 행렬 모양 변경하기

array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## 행렬 데이터 선택 : offset index(masking)

In [41]:
# 행렬 데이터 선택 : offset index(masking)
array2

array([[100, 100, 100],
       [  4,   5, 100]])

In [42]:
array2[0][::-1]
array2[1][2]

100

In [43]:
array2[1,2]  # array2[1][2] 와 같다.

100

## 데이터 수정

In [44]:
# 데이터 수정

array2[1][2]

100

In [45]:
array2[1,2]=10
array2

array([[100, 100, 100],
       [  4,   5,  10]])

## 브로드캐스팅

In [51]:
# 브로드캐스팅
array2[0]=0
array2

array([[  0,   0,   0],
       [  4,   5, 100]])

In [52]:
array2[0] = [100,100,100]
array2

array([[100, 100, 100],
       [  4,   5, 100]])

# 브로드캐스팅 _ 논리연산

In [53]:
# 조건으로 선택 -> 이것도 브로드캐스팅! 전체에 다 뿌려주는 것.

idx = array2 > 7

In [56]:
# True 인 값들만 출력해줘
array2[idx]

array([100, 100, 100, 100])

In [57]:
# 7 초과하는 값은 모두 100으로 바꿔줘
array2[idx] = 100
array2

array([[100, 100, 100],
       [  4,   5, 100]])

## 행렬 데이터 생성 (2) -> np.zeros([2,3]), np.ones([2,3]), np.arnage(1,10)

In [61]:
# 0. -> float 타입
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
# float -> int 타입 변환
data = np.zeros([2,3])
data.dtype

dtype('float64')

In [64]:
data2 = data.astype('int')
data2.dtype

dtype('int64')

In [65]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [71]:
# arange

np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])